### ISSUE TITLE
Check "date X, X by" pattern across all instances

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#10]

**Comment by bthuronyi** [comment]
Make sure each instance of "Date X" / "X'd by" is consistent across all tabs:

- "Date X'd", not "X date"
- "X'd by" uses same X as "Date X'd"
- Date column appears on the left, By column on the right
- Any exceptions have good justification

**Comment by santiagochrist** [comment]
Done! Check it out whenever you get the chance or just passively appreciate the aesthetics.
