### ISSUE TITLE
Add volume left column to Registry for GG stocks

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#101]
Add a column to the Registry showing estimated volume left for GG stock mID. Related to alternative mID suggestions, per #96

**Comment by santiagochrist** [comment]
Created column, is there a cell/tab where we can pull data on stock volume left?

**Comment by santiagochrist** [comment]
Check it out!

**Comment by bthuronyi** [comment]
Coming along! Please work in a copy rather than in the main sheet until we get the changes finalized and approved (by me, +/- others).

We need at least two changes:
- The Minipreps volumes left include all mIDs, but we instead want to index that column and pull the volume left that corresponds to the mID in the "Stock to use for GG" column, if any.
- If no mID is in "Stock to use for GG", we want to output blank (rather than 0).

**Comment by bthuronyi** [comment]
INDEX / XMATCH is a good paradigm for pulling the volume left for the given mID. There should only be one mID in the stock cell, and it should definitely be listed in mIDs since it gets extracted from there, so you can just use the cell contents directly with XMATCH and match it against the named range Minipreps_m_ID.

**Comment by santiagochrist** [comment]
This took a lot longer than it should have...
`=iferror(`
`index('Minipreps m'!$BW:$BW,xmatch($AZ1241,Minipreps_m_ID)),`
`"")`

**Comment by santiagochrist** [comment]
This took too long to solve... (using row 1241 as an example, which has mID = m3130):
`=if(`
`$AZ1241="",`
`"",`
`index('Minipreps m'!$BS:$BS,xmatch($AZ1241,Minipreps_m_ID))`
`)`

The logic is:
`is there a stock to use? if blank, do nothing (blank)`
`there is a stock to use! compare mID in Registry with mID list in Minipreps m`
`Find the value in Row BS (remaining stock)`

**Comment by santiagochrist** [comment]
**Final Code:**
`=if(`
`$AZ6="", "",`
`switch(`
`left($AZ6),`
`"m", index(Minipreps_m_Volume_left,xmatch($AZ6,Minipreps_m_ID)),`
`"o", "",`
`"d", index(dsDNA_d_Volume_left,xmatch($AZ6,dsDNA_d_ID))`
`)`
`)`
Code now handles cases with dID and oID. Now uses named ranges (Referring to the column) instead of confusing column syntax for the sake of legibility. Created the dsDNA_d_Volume_left named range.
