### ISSUE TITLE
Multifragment assembly from digest

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#102]
Currently, Gibson assembly lets use a single fragment from a digest in an assembly, but we should also support use of multiple fragment(s) potentially. See column "Second fragment sequence (from plasmid map) to assemble, overhang to overhang (not yet implemented)" on dsDNA d.

**Comment by bthuronyi** [comment]
Assemblies a also needs to handle multiple pieces from digest appropriately.

https://docs.google.com/spreadsheets/d/1xrwFnQ1eCSF4OkF8rvoMA-Njr5CS24l2QnlnsafiQio/edit?disco=AAAA36z7KB0

**Comment by evelynqi** [comment]
> See column "Second fragment sequence (from plasmid map) to assemble, overhang to overhang (not yet implemented)" on dsDNA d.

I looked within all sheets and formulas for where "dsDNA_d_Fragment_sequence_digest_1" (the first fragment sequence) is used, and there are no matches. I'm not sure how the first is implemented, so I'm not sure how the second should be implemented.

**Comment by bthuronyi** [comment]
Good strategy! But in this case it's referred to by column / individual cell rather than as a Named Range. So instead to find it, use the REGEXes from Slack:

Finding references to a column in formulas, quick reference:
This sheet:
`[^!$]\$*A[0-9:$]
`
All sheets:
`'Sheet Name'\!\$*A[0-9:$]
`replacing A with the column ID of interest and Sheet Name with the sheet containing it (or SheetName\! if no spaces).

**Comment by evelynqi** [comment]
I still cannot find matches.

**Comment by bthuronyi** [comment]
Hmm ok maybe I never implemented it, since overall digest support was not there yet either. Let's check in about what it should be used for.

**Comment by evelynqi** [comment]
It is in fact implemented -- validity checks (and the code works)! For digests that end up with more than one fragment, a new dID should be assigned to it. For Gibson assemblies that use digests that end up with more than one part would need users to enter both dsDNA parts. The problem now is how to get users to be aware of this. Implemented a message in the header to let users know to be wary to create a new dID to log the other fragments if they want them to be used in assemblies: AU1 --"If you are using multiple fragments of a single digest, you need to enter a new Serial # and log it as a separate dID". https://docs.google.com/spreadsheets/d/1pj3EE8p0EfHMjC5LHxOq8eIBKOBOVIINs4iZcbac9VY/edit?usp=sharing

Also, deleted the "Second fragment sequence (from plasmid map) to assemble, overhang to overhang (not yet implemented)" on dsDNA d column.

Also, the test case for looking at using these digests in assemblies is a841, a842, a843.

**Comment by evelynqi** [comment]
USE A NOTE INSTEAD OF HEADER, duplicate all the values and enter the sequence of the other piece

**Comment by evelynqi** [comment]
Implemented in main. The note says "If you are using multiple fragments of a single digest, you need to enter a new Serial # for each fragment, duplicate all the values, but enter the sequences of the other pieces." It is a more comprehensive message for the users. Also, it is a note instead of a message in the header for a more comprehensive message that does not compromise the amount of header space needed.
