### ISSUE TITLE
Sequencing: add warning if queued primer not listed in Registry

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#103]
If someone manually sequences with a Sanger primer not listed in the Registry options, should probably flag it (but not forbid using it).

**Comment by santiagochrist** [comment]
I added two new lines but we could just keep 1. This goes under the "Queueing Validity Check" Column.
```
=ifs(...

...)&if(not(regexmatch(K1553,I1553)),char(10)&char(10)&"primer not in registry?","")
```
I will note that this displays a "Certified OK [new line 2x] primer not in registry?" message when the Column is checked off but the primer is not pulled up from the ones in the registry. Also, what do you think about showing/not showing the warning message when the primer has already been sequenced?

Other than that, I think that's it for this issue @bthuronyi.

**Comment by bthuronyi** [comment]
> I will note that this displays a "Certified OK [new line 2x] primer not in registry?" message when the Column is checked off but the primer is not pulled up from the ones in the registry.

I think we should suppress the warning if the box is checked, i.e. put it into the IFS rather than &ing it on the end. The primer is selected during queueing, so if someone decides they want to use a non-recommended primer then certifies that, no further warning needed.

**Comment by bthuronyi** [comment]
That said, I'll go ahead and add your code in that position!

**Comment by bthuronyi** [comment]
(The complication is that there isn't a single place in the IFS to put it, actually, so instead I'm adding the warnings at the end, preceded by IF( (queueing validity check row), "", ...) to suppress them when it's checked off.

**Comment by bthuronyi** [comment]
`&
ifs(
A3="","",
P3,"",
and(regexmatch(J3,"o\d+"),not(regexmatch(J3,L3))),char(10)&"primer not listed in registry?",
TRUE,"")` at end of Queueing validity check.
Added handling for the situation where the Registry doesn't have any oIDs in it, but says "check parts present" or "whole-plasmid" or whatever. In this case, don't complain at whatever oligos are chosen.
