### ISSUE TITLE
Overhaul "mID verification" process and how it interacts with Sequencing

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#104]
Right now, someone aligning sequencing must decide that a construct is fully covered and navigate to the Minipreps tab to mark a construct mID as "verified". Consider redoing this logic flow so that the Sequencing tab can prompt someone to decide whether the mID is fully covered or needs more reads, and then have Minipreps read in that designation automatically.

**Comment by bthuronyi** [comment]
See #31

**Comment by ethanjeon** [comment]
@bthuronyi just stumped on how to account for multiple instances of the same mID having conflicting inputs in the new Sequencing prompt...

**Comment by bthuronyi** [comment]
> @bthuronyi just stumped on how to account for multiple instances of the same mID having conflicting inputs in the new Sequencing prompt...

I would (1) detect the conflict, by first checking for multiple entries within Sequencing; (2) cause Minipreps Status to change to an error message that explains the problem; (3) user has to delete one of the conflicting entries, presumably by deleting the one they just added

**Comment by bthuronyi** [comment]
Since we want to show Minipreps Status right next to this manual entry column in Sequencing, it'll appear right away, and we can format it angry

**Comment by ethanjeon** [comment]
Ok, changes are ready to implement into main CC once #141 is implemented (so we don't have to deal with overriding each other's formulas pasted in from our respective CC copies):

- [x] - NEW COLUMN - Sequencing BF - with a dropdown menu mimicking that of Minipreps' "What to do with this sample?"
- [x] - NEW COLUMN - Sequencing BG - simply mirroring Minipreps Status
- [x] - adjust "Sequencing Alignment Summary" - now Sequencing BO - to account for these two new columns inserted into a range of columns it reads from
- [x] - NEW COLUMN - Minipreps ~CY or somewhere way over to the right - which integrates both the Minipreps "What to do with this sample?" and our new mimic in Sequencing BF
- [x]       - prioritizes the original Minipreps "What to do with this sample?"
- [x]       - If there are multiple instances of an mID with conflicting selections in their Sequencing BFs, will return a warning which will also be shown in the main Minipreps Status
- [x] - update Minipreps Status to draw from this new Minipreps CY in each instance where it referred to Minipreps "What to do with this sample?"
- [x]       - new line of code placed for the warning on conflicting mID dropdowns

**Comment by bthuronyi** [comment]
- [x] Replace all references to Minipreps column H (what to do) with new column CF (integrated statuses)
- [x] on Minipreps tab
- [x] on other tabs
- [x] Replace refs to Minipreps_m_What_to_do with refs to new Minipreps_m_What_to_do_integrated_with_Sequencing

**Comment by bthuronyi** [comment]
Implemented!

> * - new line of code placed for the warning on conflicting mID dropdowns
This check looks for an exact string match to the output error and changes Minipreps_m_Status to that same error.

- [x] Add conditonal formatting on Sequencing mirror of m status for this message

**Comment by bthuronyi** [comment]
Issue: not all Minipreps Status outputs that draw on the manual status assignment directly use the manual status assignment value -- e.g. "verified" outputs a different message. So these lose the "(from sequencing)" tag.

**Comment by bthuronyi** [comment]
Looked through and to each output message that doesn't directly use CF added:
`&if(H3=""," (from Sequencing)","")`

**Comment by bthuronyi** [comment]
Appears to work!
