### ISSUE TITLE
"Sequencing results" in Minipreps doesn't pull in "sequencing failed" results

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#105]
If Sequencing read failed, "Sequencing results" doesn't collect that outcome since it may be stored only in the "Alignment classification" not also in "Alignment interpretation"

**Comment by ethanjeon** [comment]
"Sequencing results" in Minipreps pulls from "Sequencing alignment summary" in Sequencing, which gathers everything from four consecutive columns (Date interpreted, Interpreted by, Alignment interpretation, Sequencing/QC results).

Could we simply extend this range one or three columns to the left ((Date aligned, Aligned by,) Alignment classification)?  This would capture any failed sequencing results that might not be present in the alignment interpretations.

**Comment by bthuronyi** [comment]
That works, with the only disadvantage being clutter, since most "Alignment classification" values are not informative. I think better would be to check the value of "Alignment classification" and report it in the summary (instead of "Alignment interpretation") if it's a failure type. The date aligned/aligned by is also not probably very interesting/useful in the context of reviewing this summary.

**Comment by santiagochrist** [comment]
After discussing with Ethan, we figured that we need some clarification on what the cell could read from to classify a sequencing as "failure type." 

Sometimes the alignment classification has a meh read, but the interpretation ends up being fine. Other times the read is pretty rough and the interpretation is tough, and other times the read is amazing but the interpretation is good. Sometimes there are special cases classified as "Other" where we'll have to read from the sequencing/QC results.

There's a lot of variability with what should and shouldn't be considered an error type, so maybe a system of flags could work (e.g., all parts verified present = OK, some parts = AMBIGUOUS, parts missing = ERROR, etc.), maybe checking both the "classification" and "interpretation" columns, not sure. **If we purely go off "Alignment classification," to determine if it's a failure type, maybe this could work:**

```
=if(A3204="","",
iferror(join("",
if(filter(Sequencing_Alignment_classification,Sequencing_Source_ID=B3204) <> "Read completely matches map (where read quality is good)", // example criteria: if read is not perfect, then...
filter(Sequencing_Alignment_classification, Sequencing_Source_ID=B3204),  // FALSE: return classification
filter(Sequencing_Alignment_result, Sequencing_Source_ID=B3204) // TRUE: return interpretation
))))
```

**Comment by santiagochrist** [comment]
We instead decided to change the helper column (BJ), as opposed to changing the Minipreps code. We decided that if an alignment classification contains the string "Sequencing failed / not usable" then we could just output the "classification," otherwise output the "result." If notes are not blank, then concatenate that into the output as well.

**Comment by santiagochrist** [comment]
Final Code ('Sequencing'!BJ3):
```
=if(
AY3<>"",if(AX3=index(settings_SequencingAlignmentCategoryOptions, 1), // written this way to future-proof it.
join(" - ", J3, AX3, BB3:BC3), // Seq Failed: TRUE (return less info)
join(" - ",J3,AY3:BC3) // Seq Failed: FALSE (return more info)
), ""
)
```
