### ISSUE TITLE
Minipreps "Is sequencing appropriate?" should throw an error if actual color <> expected color

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#107]
Minipreps "Is sequencing appropriate?" should throw an error if the recorded actual color after growth is not the same as the expected color.

**Comment by santiagochrist** [comment]
I have written a solution that compares data from Column Q ("Intended color") and Column Y ("Growth/color notes"). While my solution works, the main issue is that many of the notes may reference the expected color but still not match the string (i.e., expected color is red, but 'light red' is written on the growth color notes).

**Comment by santiagochrist** [comment]
A solution might be to scan through the string to see if there is a match (i.e., see if we can find "red" in the string "light red"). At that point, though, how should we handle a case where multiple colors are written down (i.e., purple is expected but white/purple was written)? Or if an alternate way or synonym of a color is used (i.e., "violet" or "purplish" would both throw an error if "purple" is expected). In these cases, the protocol should mention that we have to be exact in our description, but we can't exactly modify the thousands of entries before the latest entry, so a good 2000 ish entries would throw out a "ERROR: COLOR MISMATCH" kind of message in the "Is sequencing appropriate?" column.

**Comment by bthuronyi** [comment]
> I have written a solution that compares data from Column Q ("Intended color") and Column Y ("Growth/color notes"). While my solution works, the main issue is that many of the notes may reference the expected color but still not match the string (i.e., expected color is red, but 'light red' is written on the growth color notes).

I think this is a strong first step. If we presume that sometimes the growth phenotype recorded won't exactly match even when they are basically equivalent, we can have "is sequencing appropriate" return "check growth phenotype" rather than "no", and kick it back to users to inspect manually.

We can also institute a behavioral control where we expect users to enter the exact color string if it grows as expected. This seems not great, though, because behavioral controls are not great, there wouldn't be a clear way to message/prompt this behavior right in CC, and often users may want to record useful information e.g. shades of color that differ between preps.

Another option is to **add a new column** of required user input, which has a dropdown and asks users whether the growth phenotype matches expectations. (Would need a concise name for this). They could select "yes", "no" or "maybe". In fact, we could **combine these options** with the existing "Grew?" column, and expand its options to: "yes, color/phenotype as expected", "yes, color/phenotype not clearly expected", "unexpected color/phenotype", and "no". That might be the best option, since we already require users to fill this column in!

What do you think?

**Comment by bthuronyi** [comment]
> In these cases, the protocol should mention that we have to be exact in our description, but we can't exactly modify the thousands of entries before the latest entry, so a good 2000 ish entries would throw out a "ERROR: COLOR MISMATCH" kind of message in the "Is sequencing appropriate?" column.

Though I agree this isn't the way to go, FYI we have previously taken the time to algorithmically or semi-manually update past data to conform to new standards, so if we do decide it's worth it, there's precedent.

**Comment by santiagochrist** [comment]
`=if(A3335="","",lambda(x,
ifs(
$R3335<>$V3335, "Check growth phenotype", // prompts user to check
join("",x)="OK","Likely OK to sequence",
iferror(match("Problem",x,0)),"Do not sequence",
TRUE,"Check QC data"
))
(iferror(...))`

**Comment by santiagochrist** [comment]
**Is sequencing appropriate?** (Row 3290)
`...`
`OR(join("",x)="OK", $Y3290="yes - color/phenotype DO match"), "Likely OK to sequence", // check if color matches`
`$Q3290<>$Y3290, "Check growth phenotype", // if not, prompts user to check`
`...`

**Grew?** Options: 
`yes - color/phenotype DO match`
`yes - color/phenotype DO NOT match`
`unexpected color/phenotype`
`no`

**Comment by santiagochrist** [comment]
I have this solution on my copy of CloneCoordinate, let me know if you'd like to test it out on live CC!

**Comment by santiagochrist** [comment]
As a summary, we went through and manually sorted old data on Monday afternoon. B used a piece of code that narrowed down the "cells that needed edits" from ~2000 to ~200, so we raced to finish it ASAP. Code works well now.

**Comment by bthuronyi** [comment]
> As a summary, we went through and manually sorted old data on Monday afternoon. B used a piece of code that narrowed down the "cells that needed edits" from ~2000 to ~200, so we raced to finish it ASAP. Code works well now.

We first filtered for rows where the color didn't match the expectation exactly and where growth color notes were filled in. Then checked for rows where the color wasn't a substring of the growth color notes. Finally, manually chose drop-down options that fit the growth color notes relative to the expected color.
