### ISSUE TITLE
Transformations should warn about duplicate queued/completed transformations

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#108]
In Status or Queueing validity check, inform user about whether this entity has previous been transformed or queued to be transformed and warn if so.

**Comment by ixf1** [comment]
and(U4="", countif(C:C, C1) < 2), "Ready to transform",
and(U4="", countif(C:C, C1) > 1, countif(C:C, C1&U4) > 0), "Ready to transform and has previously been transformed",
and(U4="", countif(C:C, C1) > 1, countif(C:C, C1&"<>") > 0), "Ready to transform and has previously been queued",

It works but it is a little long.

I replaced U4="","ready to transform", with this.

**Comment by ixf1** [comment]
New code:
U3 = "", 
if(countif(Transformations_Source_ID, A3) = 1, "Ready to transform", 
if(counta(iferror(filter(Transformations_Source_ID, Transformations_Source_ID = A3, Transformations_Date_transformed > 0))) > 0,"Ready to transform and has previously been transformed", 
"Ready to transform and has previously been queued")),

replacing same line. will implement now!
