### ISSUE TITLE
Checkboxes in Asst: sheets should be hidden when component name is empty

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#112]
As implemented in Asst: dsDNA, all checkboxes should be formatted as white foreground + white background in Asst: sheets when the component information next to them is blank.

**Comment by bthuronyi** [comment]
Copy over conditional formatting from Asst: dsDNA to other Asst tabs and adjust the ranges based on checkbox positions.

**Comment by ixf1** [comment]
![image](https://github.com/bthuronyi/CloneCoordinate/assets/173081691/1e797385-7cbf-4ac4-90f3-8020b4e434df)
I just used the code from Asst: ds DNA to do this. I did it for Asst: Assemblies and can do it for more.

**Comment by ixf1** [comment]
https://docs.google.com/spreadsheets/d/1zGIvgbo6z5WToRgEdXGMX7BIs0NH9mEj12pw4ylbjRc/edit?gid=345208367#gid=345208367

I only implemented this change to one other Asst sheet (Asst: Assemblies). I thought it would be a bad use of time to implement it on every Asst tab on my copy of CC.

**Comment by bthuronyi** [comment]
Looks great! Agreed, no reason to implement on a copy any further. Go ahead and implement on Asst tabs on the main CC as you did here.
