### ISSUE TITLE
Experiment Registry

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#116]
Implement an Experiment Registry where:

- users queue up Experiments that reference multiple registered Constructs and describe a plan for what to do with them
- tracks progress of those Constructs through pipeline
- maybe Tracker can read from it to classify uncompleted constructs by Experiment
- emails registered person automatically (soon to be introduced Google Sheets feature, June 2024!) when all constructs are ready

**Comment by bthuronyi** [comment]
Existing prototype (key code isn't functional though):
https://docs.google.com/spreadsheets/d/1V-dNTPkBbCBVYFdF2Yk1ACB9XifOFYA6i7nfBQDyptk/edit?usp=drive_link

**Comment by shen2333333** [comment]
https://docs.google.com/spreadsheets/d/1V-dNTPkBbCBVYFdF2Yk1ACB9XifOFYA6i7nfBQDyptk/edit?usp=sharing

Mostly functional now . 

"Construct ready" column seems broken, can't correctly identify status of a particualr construct.

**Comment by bthuronyi** [comment]
Looks like this is now working great! Awesome. Because the prototype was written at an earlier time point, it's not in compliance with our developing coding style conventions for external sheets, so we should get it into compliance before moving forward with it (as we're doing with the Tracker), but I think this is basically almost done...!!

**Comment by bthuronyi** [comment]
- Updated compliance with Imported-data conventions - added Named Ranges to formulas
- Fixed construct status lookup - use INDEX/XMATCH instead of FILTER/COUNTIF (the former seems to work with ARRAYFORMULA but the latter doesn't)
- Added warning if any construct(s) are marked "abandoned" -- in this case the experiment is killed, needs manual intervention to cancel it or change the constructs

**Comment by bthuronyi** [comment]
@evelynqi @ixf1 @ethanjeon @santiagochrist Please review the linked sheet and try adding an experiment, see if it makes sense and whether you have suggestions

https://docs.google.com/spreadsheets/d/1V-dNTPkBbCBVYFdF2Yk1ACB9XifOFYA6i7nfBQDyptk/edit?usp=sharing

**Comment by bthuronyi** [comment]
One thing that occurred to me is that some "experiments" want particular CC operations to be done, but not necessarily for constructs to be finished. And that situation might be relevant to more labs than just us, if someone wants to manually intervene once CC reaches a certain state. What's tricky is that it's hard to generally define what kinds of entities and status changes someone might want... might need a more flexible architecture than this and therefore more annoying to code... so could save it for a later version

**Comment by santiagochrist** [comment]
Does the email notification feature currently work? Other than that, I added my fake experiment and put my two pending constructs, and everything seemed to have gone smoothly. 

Would we want to add something like "related experiments" or "collaborators" or "species tested," etc.?

**Comment by bthuronyi** [comment]
> Does the email notification feature currently work? Other than that, I added my fake experiment and put my two pending constructs, and everything seemed to have gone smoothly.

Nope, doesn't work yet, but it's supposed to roll out to our Google enterprise instance within the next few weeks sometime.

**Comment by bthuronyi** [comment]
> Would we want to add something like "related experiments" or "collaborators" or "species tested," etc.?

"Related experiments" does sound promising. For the other stuff, we likely want to defer to notebook entries rather than getting too granular in this Sheet (for now). The primary purpose of this is to connect constructs-being-cloned to experimental needs, rather than to document/track all experimental work being done.

**Comment by bthuronyi** [comment]
"Conditional notifications" has now rolled out to our Google domain! I will try it out.

**Comment by evelynqi** [comment]
I tested it, the "Construct statuses" seems bugged...

**Comment by evelynqi** [comment]
I would want it to be filterable, like how the tracker is, so I can filter for experiments of a certain "experiment type" or "queued by" a specific person, or perhaps even past a certain "queued by" date.

**Comment by bthuronyi** [comment]
> I tested it, the "Construct statuses" seems bugged...

Nice catch!! Looking into it. Nonsense / non-registered constructs are showing up as "complete"...??

**Comment by bthuronyi** [comment]
> Nice catch!! Looking into it. Nonsense / non-registered constructs are showing up as "complete"...??

One problem here: ARRAYFORMULA was not behaving as expected when an array was used with INDEX( ... XMATCH(array ...)). Instead it apparently just outputted the results from the match to the first member of the array.

I fixed this by changing to BYROW instead of ARRAYFORMULA. That might be the best practice at this point anyway since BYROW is much more transparent in terms of what it will do.

**Comment by bthuronyi** [comment]
Second bug, now fixed: the check for completion was comparing an _array_ and a _filtered array_ to see if all elements in the array contained "complete". However this didn't work as expected; it returned TRUE even when the arrays were different, I think if their first elements matched. Adding ARRAYFORMULA didn't fix that behavior.

Instead, the formula now uses COUNTA on the array vs. the filtered array and compares the counts. This works as expected.

**Comment by bthuronyi** [comment]
Email notifications are erroring, I'm looking into that. However there's another potentially bigger issue, which is that the IMPORTRANGE source for the data may mean these notifications don't update as automatically as we would want... This might mean we need to put the Experiment Registry into CC itself, which wouldn't be too bad.

![image](https://github.com/user-attachments/assets/43b9a845-0254-486c-b5fa-08b96a78644f)

**Comment by bthuronyi** [comment]
> I would want it to be filterable, like how the tracker is, so I can filter for experiments of a certain "experiment type" or "queued by" a specific person, or perhaps even past a certain "queued by" date.

I think the best way to do this is in a different tab / external Sheet. In order to filter as is done in the Tracker, you have to source the data with a formula, so it can't be done directly on a write-able tab.

That said, let's file this as a new Issue for the future. Based on the behavior of Conditional Notifications, it looks like putting the Experiment Registry (I will name it Experiments) directly into CC is best. A filtered version could conveniently live in the Tracker or in its own dedicated sheet.

And to be honest, even if Conditional Notifications handles changes triggered by IMPORTRANGE (reading the wording carefully, it might indeed work ok, since the cell we're notifying about draws on OTHER cells that use IMPORTRANGE but doesn't directly IMPORTRANGE itself), it feels reasonable that experiments be registered directly within CC, since that data is part of what we will want to track and preserve along with cloning info. If this were an external Sheet, it would be the only one that users are expected to archive and keep information in.

**Comment by bthuronyi** [comment]
Because of how the code is implemented, all the formulas can simply be copied over verbatim after copying the tab into main CC.

**Comment by bthuronyi** [comment]
Now implemented in live CC. File bugs or suggestions as new Issues, and try it out with _real_ experiments!
