### ISSUE TITLE
Assemblies status inappropriate "ready to queue miniprep"

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#117]
In this copy, a941 and a942 say "ready to queue miniprep" when they were just transformed (no plates scored).

https://docs.google.com/spreadsheets/d/1bi6iTMQDwBp9nBWYIpv4fsKlT5cQYOkN-M4jvpzlJgc/edit?usp=drive_link

**Comment by ethanjeon** [comment]
It displays the correct "ready to score plates" in that version of the sheet right now...

The relevant line of code is _and(BT944="",value(text(today(),"yymmdd"))-value(BS944)>0),"ready to score plates",_

The only way I think this error could have happened is maybe whenever plate scoring is attempted on the same day transformations are done (we've done this many times, probably without this error...) or the wrong transformation date was entered?  Not really sure what happened.

**Comment by santiagochrist** [comment]
Tested the case where the transformation date is 240702, and yes it indeed seems that the "TODAY" - "TRANSFORMATION DATE" > 0 condition is what's causing this issue. 

I think a simple `and(BT944="",value(text(today(),"yymmdd"))-value(BS944)>=0)` might be appropriate considering that this line just checks whether the entered dates are valid (i.e., you didn't somehow transform before queueing the assembly in the first place).

**Comment by santiagochrist** [comment]
Checked with B, add the bottom line to ensure that an incubation wait period is present: 
```
and(BT945="",value(text(today(),"yymmdd"))-value(BS945)=0),"wait on incubation",
BT945="", "ready to score plates",
```
