### ISSUE TITLE
audit golden gate premix

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#123]
audit golden gate premix on assistant sheet

**Comment by bthuronyi** [comment]
https://docs.google.com/spreadsheets/d/1ziLDJyqw1qKeowfPWMGHoT_diWgqxYsWNtYaOVb__Yg/edit?gid=1540456475#gid=1540456475

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1O8Lp268wTBJHQs242kHXhCU1ayhEZRmO4Oi8lVBwGAc/edit?usp=sharing
we audited :)
