### ISSUE TITLE
Rework Tracker formulas to comply with code guidelines

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#124]
Rework ("refactor") Tracker Formulas to comply with code guidelines / best practices, to be shared by @ethanjeon. No changes in output needed yet.

**Comment by shen2333333** [comment]
Got it

**Comment by shen2333333** [comment]
https://docs.google.com/document/d/1JzvcSNAfCQBsOLyTi0fPx-CZsf0w3VudGrVEUC-oG_4/edit?usp=sharing

Made a google doc refresh myself about the tracker I did, and some things I could do to "refactor" as needed.

**Comment by shen2333333** [comment]
Comment from Ethan, to work on 
Ok, so it looks like B and I did add that new column Y of gIDs, you can remove it along with the blank column X we also added since they're disrupting functionality
Screen Shot 2024-07-06 at 12.56.23.png
 
Screen Shot 2024-07-06 at 12.56.23.png








[10:08](https://thuronyilab.slack.com/archives/D07A12SNEE9/p1720285690449549)
I think B just didn't like having sorted and non-sorted columns right next to each other.  I'm not sure how to resolve this, and I can tell the Tracker mostly works the way it's set up right now.  Is there any way to reorganize things, or make a better visual distinction between sorted and unsorted blocks of columns?
this was what made B insert the blank column X and gID column Y, to separate what appeared to be a large block dealing with constructs and another one dealing with gIDs... to reorganize the code to look a bit more like how CloneCoordinate is set up
Screen Shot 2024-07-06 at 13.04.59.png
 
Screen Shot 2024-07-06 at 13.04.59.png


[10:10](https://thuronyilab.slack.com/archives/D07A12SNEE9/p1720285815677309)
Other than making that distinction more clear, I would suggest fixing the hard-coded 7 attempts in Construction Summary, stuff like that?  I don't think there are too many more fundamental structural changes to be made

**Comment by bthuronyi** [comment]
The main structural issue I see is that the Formulas tab has a lot of formulas that are referring to columns on Imported-data, instead of Named Ranges (best option) or columns on Formulas. Here, for example:
![image](https://github.com/bthuronyi/CloneCoordinate/assets/141874213/eef8b3fb-f045-49f1-a34e-1fc0b4f27054)

1) That's a problem in itself -- Formulas should only refer to other Formulas columns or to Named Ranges
2) Here, a Formulas column (G) is being indexed according to a match to a _different column_ that coincidentally happens to be organized in the same order as G. Instead, Formulas G should be indexed to Formulas A, and indexed according to matches to Formulas A. Everything in this block of columns should be indexed to the first column in it (A). If you need another block besides the one indexed to A, you could add its own leftmost index column and set it off so it's clear it's a new indexing column.

**Comment by bthuronyi** [comment]
The reason for (1) is that we want the code to be portable -- to draw only on Named Ranges for CC data, and to not care how/where the Named Range data is imported. That allows us to redo how Imported-data is laid out without rewriting any code. The way things are now, if we were to use a script to update Imported-data by reordering imported columns or removing those not referred to by the Tracker, it would break the code unless we implemented pretty sophisticated checks. It also means we can reuse code from different support sheets easily by just copying and pasting it into a different support sheet.

**Comment by bthuronyi** [comment]
The reason for (2) is that someone reading the code has to look outside of the current tab to understand what Imported-data!G:G is, and there's no obvious guarantee that the order of entries in Imported-data!G:G will always match the order of entries in Formulas G. It makes debugging challenging if anything goes wrong and it makes all the formulas harder to parse. Named Ranges on the other hand make the formulas readable without needing to check what a column contains, since the name tells you what it is.

**Comment by bthuronyi** [comment]
One criterion for the code to be in compliance is that the following search will come up with no hits:
![image](https://github.com/bthuronyi/CloneCoordinate/assets/141874213/d74caaae-58b3-4543-b56d-dbc8fdf631b3)

**Comment by shen2333333** [comment]
I took a look and I think I understand, it should be flushed out in 2-3 days.

**Comment by shen2333333** [comment]
Making good progress today, ~50%, mainly rephrase formula to eliminate reference to imported ranges and use named ranges whenever possible.

**Comment by bthuronyi** [comment]
Coming along, the changes are helpful! One other thing that might help both organize and make the code more readable: could you use some kind of formatting -- cell background, border, whatever -- to group columns according to the "anchor" column which gives their corresponding identifier(s)? That would likely be more useful than the original background color which I think is about source tab.

**Comment by shen2333333** [comment]
@bthuronyi @ethanjeon Refactor draft done, please check when you get a chance! I know next step would be flush out the named ranges in main sheet; and get the tracker up to date on USER --> assembly changes, so will do that once refactor is confirmed.

**Comment by shen2333333** [comment]
What I did
1. Within a formula, if there's reference to columns in "imported ranges", I change them to either named ranges or reference within the same tab. If I need to reference columns within the same tab, the referenced column will be on the left of the current column.
2. I redo the color coding so that there's "blocks" for the usual dna pieces (dsDNA, USER, GG, Miniprep, Sequencing) and a purple block for more complex formulas compiling information from the dna pieces. And at the most right, I have those 3 sorted columns based on alphabet that's used in the main tracker. 

feedback welcome

**Comment by bthuronyi** [comment]
Coming along! I still see places to add an "anchor column" that gives the sort IDs that go with a block, e.g. Formulas!B looks like it's anchored to Formulas!A but is actually anchored to dsDNA_d_Num (not shown). I would add a new column in between, put {dsDNA_d_Num} in its row 1, and then color it the same as the cells to the right. All those Named Ranges are by definition ordered by dsDNA_d_Num.

**Comment by bthuronyi** [comment]
I also see some problems with Named Range conventions across Imported-Data that could cause real trouble. The convention is that the entire column, e.g. A:A, gets the Named Range name that matches its row 1 importrange argument. But instead many (but not all!) Named Ranges start at row 3. Although it can be annoying sometimes to deal with the headers, we need all those Named Ranges to be full-column. This is because *only Named Ranges that span an entire column get redefined as the full column if new rows are ever added*. So we need to use them that way in CC and therefore should be consistent in accessory sheets like the Tracker as well -- code must assume Named Ranges are full-column everywhere to be portable.

**Comment by bthuronyi** [comment]
We could probably script updating the named range definitions fairly quickly, but also just clicking through and redefining them would also only take 10 mins probably.

**Comment by bthuronyi** [comment]
I found some #REF errors in formulas and tried to fix them, but perhaps because of the named range length inconsistencies the Tracker is broken even with the #REFs filled in. I think before worrying about debugging we should update the Named Range definitions and see what that fixes.

**Comment by shen2333333** [comment]
I see. I changed the named ranges to full columns. But I'm not sure how to tackle to issue with headers.

So for example my column A is "d summary" and has this formula. 

=ArrayFormula(IF(dsDNA_d_Num="", "", 
    dsDNA_d_Type&"/"&dsDNA_d_ID&"/"&dsDNA_d_Oligo_1&"/"&dsDNA_d_Oligo_2&"/"& 
   dsDNA_d_Status&"/"&dsDNA_d_Polymerase&"/"&dsDNA_d_Variation_additives&"/"&dsDNA_d_Anneal_temp&"/"& 
   dsDNA_d_Num_of_cycles&"/"& dsDNA_d_Date_finished&"/"& dsDNA_d_gel_quality&"/"& dsDNA_d_Gel_result&"/"& 
   dsDNA_d_Conc)
)

I tried to use arrayformula so it's one formula for entire column. If I use named ranges from "imported-data" tab, it will try joining the "headers" which won't make sense,  leads to REF error and that's why I attempted modify the named ranges. I wonder what I could do to get around this problem. Perhaps I could have another helper function to not include the header?

**Comment by bthuronyi** [comment]
I would instead just pull each column you want to combine by putting ={dsDNA_d_Num} etc. in each row 1, then after all those columns, put in row 3 and below: `=join("/",A3:M)` or something like that.

**Comment by bthuronyi** [comment]
If you want to do it as a single column, there are a few ways to approach it. I think it would be ok to include the headers, because ideally you are going to INDEX this column by dsDA_d_Num or ID or similar, so you will never pull the header rows.

**Comment by shen2333333** [comment]
"I would instead just pull each column you want to combine by putting ={dsDNA_d_Num} etc. in each row 1, then after all those columns, put in row 3 and below: =join("/",A3:M) or something like that."

I liked this idea, and restructured the sheet, putting blank columns in between to signify blocks. I colored the columns green for columns I simply pulled from imported-data using named ranges, for blue columns I did formulas on those green columns. After that, I had a block of purple columns for additionoal formulas done on the blue columns and the rightmost block is the output for the tracker

**Comment by bthuronyi** [comment]
Nice, that looks great! It is now easy to tell what's collected from what and to modify the individual sections. So the finishing touches are:
- Move to only Named Ranges for columns referenced from Formulas that reside in Imported-data -- with that change, we can script updates to Imported-data without worrying about column order
- I was actually unfamiliar with the syntax you used to reference a full column named range. I think it is easier to read if you use e.g. `={dsDNA_d_ID}` vs. `=dsDNA_d_ID:dsDNA_d_ID` even though they appear to be equivalent. The issue is that Sheets doesn't automatically label the second version as a named range. Please switch over just so we maintain consistent code style.
- We can also improve readability by moving some "constants" referenced by formulas to their own section of Formulas, with cells next to them to explain what they do. I moved the d summary labels and put an explanation on the far left as an example.

I don't know yet what other changes to the code might be helpful but this is a firm foundation for modifying it.

**Comment by shen2333333** [comment]
Sounds good, can you explain more about "Move to only Named Ranges for columns referenced from Formulas that reside in Imported-data -- with that change, we can script updates to Imported-data without worrying about column order"?

**Comment by bthuronyi** [comment]
Sure -- so if we remove any references to Imported-data that aren't named ranges -- e.g. replace `={'Imported-data'!BA:BA}` with `{USER_u_ID}` -- then references to Imported-data no longer have any dependence on what column stores what data. Only the Named Range names specify what's what.

That's helpful because if we need to update Imported-data we have a strong handle on how to do so:

1. We can delete all the formulas and Named Ranges in Imported-data and rebuild them from scratch using the latest Named Ranges in CC (e.g. if more Named Ranges are added to CC making the Tracker out of date)
2. We can check what data is actually used by Formulas / the Tracker generally by searching for each Named Range within formulas (this can be done using a regex) and are guaranteed that if a Named Range doesn't appear in a formula, that data isn't used
3. (2) allows us to delete unused imported columns to increase the sheet's efficiency, if needed at some point (though so far it seems like it's not slowed down even by a lot of importrange calls)

**Comment by bthuronyi** [comment]
> One criterion for the code to be in compliance is that the following search will come up with no hits: ![image](https://private-user-images.githubusercontent.com/141874213/347052784-d74caaae-58b3-4543-b56d-dbc8fdf631b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTI1NTMsIm5iZiI6MTcyMTY1MjI1MywicGF0aCI6Ii8xNDE4NzQyMTMvMzQ3MDUyNzg0LWQ3NGNhYWFlLTU4YjMtNDU0My1iNTZkLWRiYzhmZGY2MzFiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxMjQ0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjYwYzEzZWY2ZDhhNTZiODMxYWZiNDI3MmM1OWNmNjcyMGJkZDBiYzg2ZGY4MzUyOWRjM2ZiOWFkNDk3ZTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qZmwATXW8ktHTpNMe9SNZFmzAQCxAI5fEFeQ8YAD2iw)

Again this is the criterion we want to meet: zero references to Imported-data per se and instead only Named Range use.

**Comment by shen2333333** [comment]
Thanks for the explanation!

1. I made sure there's no reference to imported ranges, and changed =dsDNA:dsDNA to {dsDNA} (I actually didn't realize there's a easier way haha and did the hard way first)
2. I put the labels in the leftmost area. 

Should be mostly flushed out for now... later modification can be done depend on the need.

**Comment by bthuronyi** [comment]
Nicely done!
