### ISSUE TITLE
Asst: GG doesn't handle premix well when mIDs/volumes not entered

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#125]
Asst: GG needs to hold its horses on showing a premix calculation until all volumes and mIDs are entered,

**Comment by bthuronyi** [comment]
https://docs.google.com/spreadsheets/d/1ziLDJyqw1qKeowfPWMGHoT_diWgqxYsWNtYaOVb__Yg/edit?gid=1540456475#gid=1540456475

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1O8Lp268wTBJHQs242kHXhCU1ayhEZRmO4Oi8lVBwGAc/edit?usp=sharing
Added header for user interpretation.
