### ISSUE TITLE
dsDNA "digest" type support

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#127]
Asst: dsDNA current provides no calculations to support "digest" type dsDNA building. Users are expected to do it offline. Furthermore, no info is stored as of now about how much of each enzyme is used or how long the digest runs. We should add support that (1) tracks this info; (2) pulls relevant info onto the Asst: dsDNA tab; and (3) ideally, eventually, covers premixes where relevant.

It would be reasonable to force the Asst: dsDNA tab to require that only digests are queued to enable these features (and that only PCRs or only anneals are queued, for those).

**Comment by bthuronyi** [comment]
dsDNA "Status" and "Queueing validity check" don't appropriately check "Type" for "digest" and handle things appropriately. Instead "digest" type is handled like a PCR, inappropriately.

**Comment by evelynqi** [comment]
> dsDNA "Status" and "Queueing validity check" don't appropriately check "Type" for "digest" and handle things appropriately. Instead "digest" type is handled like a PCR, inappropriately.

This is also the case for "anneal" type.

**Comment by evelynqi** [comment]
> dsDNA "Status" and "Queueing validity check" don't appropriately check "Type" for "digest" and handle things appropriately. Instead "digest" type is handled like a PCR, inappropriately.

I've implemented code that checks for "digest" type. So far, it checks for whether the template exists and is ready and that all the digest queueing boxes are filled in. In theory, the other things we can check for are 1. whether the restriction enzyme site exists on the template DNA 2. whether the fragment sequence matches a sequence on the template DNA but I don't think we currently store plasmid full sequences.

**Comment by evelynqi** [comment]
> So far, it checks for whether the template exists and is ready and that all the digest queueing boxes are filled in.

Turns out the same code that looks at the template exists in both "queueing validity check" and "status" of the dsDNA sheet. Therefore, when I fixed it in the "queueing validity check" cell, the status was still incorrectly giving the status of "digests".

**Comment by evelynqi** [comment]
> how much of each enzyme is used or how long the digest runs

"Typically, a restriction digest involves the incubation of 1 µl of enzyme with 1 µg of purified DNA in a final volume of 50 µl for 1 hour". I'm thinking we wouldn't need to add new columns into dsDNA, but maybe use existing columns, like actual elong to log how long the digest runs, but we can add columns to the Asst: dsDNA sheet that pulls from existing columns for things like enzyme and buffer. Could we edit "Amount of premix for this PCR & premix name" column (CN) in asst: dsDNA sheet to account for "digest" types. So far, the code is: 

=if(BM3="anneal","Annealing buffer "&FORMAT_FOR_PIPETTING(settings_dAnnealBufferVolume),
if(CL3,
"Premix "&char(match(CB3,$CC$3:$CC,0)+64)&" "&FORMAT_FOR_PIPETTING(CM3)&" µL"
,""))

I'm thinking that since we have something for anneals, we could do something for digests that is just buffer and enzyme if the buffer and enzyme are the same (in the same concentrations). If not, we may be able to add it to the "additional component(s) row.

**Comment by evelynqi** [comment]
> It would be reasonable to force the Asst: dsDNA tab to require that only digests are queued to enable these features (and that only PCRs or only anneals are queued, for those)

I think that if we were able to do what I mentioned above, it would also be reasonable that digests, PCRs, and anneals could be queued at the same time. The amount of template to add is determined in the header. This message could be specified for "digest" and "PCR".

**Comment by bthuronyi** [comment]
> In theory, the other things we can check for are 1. whether the restriction enzyme site exists on the template DNA 2. whether the fragment sequence matches a sequence on the template DNA but I don't think we currently store plasmid full sequences.

Good ideas for v2.0 features, since yes, at the moment we don't store full plasmid sequences but I'm definitely thinking about doing so.

**Comment by bthuronyi** [comment]
> Turns out the same code that looks at the template exists in both "queueing validity check" and "status" of the dsDNA sheet.

Overall, I think our goal is to put a single copy of any code that looks at conditions that can change between queueing and "ready to" status into Status, not in Queueing validity check. But there may well be some duplications as of now. @ethanjeon #134

**Comment by bthuronyi** [comment]
> I'm thinking we wouldn't need to add new columns into dsDNA, but maybe use existing columns, like actual elong to log how long the digest runs,

I agree this is feasible in principle but I'd prefer to avoid doing it for reasons of transparency/ease of use. If a column is "overloaded" in this way, users have to understand that (and we do, when parsing it later). If there's a clear generic title we can give the column that covers both use cases, then no problem. In this case, though, "incubation time" is what you'd want for digest, and that doesn't fit PCRs -- elongation time is one step in a PCR program that gets repeated multiple times, so that feels different to me than total incubation time.

Let's go ahead and add an "incubation time" for digests only. I'm using conditional formatting in dsDNA d to gray out fields that are required (green header) but shouldn't be filled in for particular types, and we can make the "incubation time" field grayed out for PCR and anneal types.

**Comment by bthuronyi** [comment]
> we can add columns to the Asst: dsDNA sheet that pulls from existing columns for things like enzyme and buffer. Could we edit "Amount of premix for this PCR & premix name" column (CN) in asst: dsDNA sheet to account for "digest" types. So far, the code is:
> 
> =if(BM3="anneal","Annealing buffer "&FORMAT_FOR_PIPETTING(settings_dAnnealBufferVolume), if(CL3, "Premix "&char(match(CB3,$CC$3:$CC,0)+64)&" "&FORMAT_FOR_PIPETTING(CM3)&" µL" ,""))
> 
> I'm thinking that since we have something for anneals, we could do something for digests that is just buffer and enzyme if the buffer and enzyme are the same (in the same concentrations). If not, we may be able to add it to the "additional component(s) row.

Yeah, I think this is a sensible approach -- just "hard-code" the digest ingredients as is done for Anneal, pulling from the dsDNA d columns. Right now there is no "volume" column for the enzymes -- I think we should probably add one to dsDNA d, and have a default value (in the header) in Settings. Then you can pull from that for Asst: dsDNA.

**Comment by bthuronyi** [comment]
> The amount of template to add is determined in the header. This message could be specified for "digest" and "PCR".

Trouble is, this is for PCRs where all templates are added in the same amount. Digests will almost certainly call for different volumes of template.

I think instead, let's get rid of that header and instead make the "Template DNA" columns act like the "Oligo 1" and "Oligo 2" columns do -- give a well AND a volume, per row. Then the "template volume" column can be used for digests and show different volumes on each row. For PCRs, it can just display the same value in each row, derived from the place the header gets it. I think honestly that is more ergonomic and transparent anyway!

**Comment by evelynqi** [comment]
So far: 
-Added a new column to CC(AU--Actual incubation (m:ss)-- dsDNA_d_Actual_incubation). I added these cells to the existing conditional formatting for graying out cells for different types. 

https://docs.google.com/spreadsheets/d/1mj7P8Z2oMiGSHJ5T7a3W8WW0ULPlM9Ebr29A8_vcAVo/edit?usp=sharing
In my copy, I have:
-Added into settings some dsDNA digest default values, like settings_dDigestBufferVolume and settings_dDigestEnzymeVolume
-Added Enzyme 1 Volume and Enzyme 2 Volume to dsDNA sheet (has conditional formatting) (Z, AB)
-Added Enzyme 1 and Buffer to mix components table in Asst: dsDNA (BZ, CA)
-Changed formula in mix combinations (CD) to account for digest/buffer combinations

=if(BS4="",
ifs(
and(BV4<>"",$BW4<>""),BV4&"|"&$BW4,
and(BZ4<>"",$CA4<>""),BZ4&"|"&$CA4,
TRUE,""))

-Changed CG and CH to "Component of premix" and "Second component of premix" to account for digest mixes
___________________________________________________________________________________________________________________________________
To do: 
__fix CI --> on the Asst sheet to handle digest conditions
__fix header to handle digests separate from anneals/PCRs

**Comment by evelynqi** [comment]
Note for mix combinations (not used)

=if(BU8="",
ifs(
and(BX8<>"",BY8<>""),BX8&"|"&$BY8,
and(CC8<>"",CE8<>""),CC8&"|"&CE8&if(CD8<>"",CD8,""),
TRUE,""))

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1bzumeOTEN57T3ak3pbLISh5hERLXs2nSg6Wq2Fliesw/edit?usp=sharing

Asst: dsDNA

I didn't get rid of the "digest not handled in asst sheet currently" flag in the banner yet -- but I think it's implemented. Enzyme and buffers are added to the "additional component(s) to add" and the volumes are pulled from the settings tab. I did make a new table for this but I think it would also be reasonable to add the volume vols to the assisting enzyme/buffer lists? It accounts for one buffer and up to two restriction enzymes.

**Comment by evelynqi** [comment]
- [x] uniform template µL implement in asst (title generic--input dna)
- [x] like the golden gate calc and actual (mID and volumes) for digests but not for PCRs in normal dsDNA
- [x] get rid of settings table of enzymes but keep for buffer (diff buffers, concentrations can be diff)
- [ ] buffer/enzyme compatibility suggestion type of thing (for later..alert if it doesn't match is one possibility in queueing validity check in dsDNA)

**Comment by bthuronyi** [comment]
Also I can't believe it took me this long to think about this, but we should make sure that Digest "Input DNA" can be a dID as well as an mID. Or even an oID actually (for the special case of gblocks that are ordered as oligos; in this case Oligos_o_dsDNA_or_ultramer? must be TRUE).

**Comment by evelynqi** [comment]
> Also I can't believe it took me this long to think about this, but we should make sure that Digest "Input DNA" can be a dID as well as an mID. Or even an oID actually (for the special case of gblocks that are ordered as oligos; in this case Oligos_o_dsDNA_or_ultramer? must be TRUE).

DONE -- queueing validity check (AJ) Takes into account multiple sources of template DNA. Gives "DNA template not appropriate for digest!" for non gblock oIDs
https://docs.google.com/spreadsheets/d/1bzumeOTEN57T3ak3pbLISh5hERLXs2nSg6Wq2Fliesw/edit?usp=sharing

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1bzumeOTEN57T3ak3pbLISh5hERLXs2nSg6Wq2Fliesw/edit?usp=sharing

Asst: dsDNA tab is now set up for digest! 

1. The enzyme and buffers are set up as additional component(s) that don't need premixing. Volumes are drawn from what the users queued during queueing.
2. Changed col Z in asst to generic input DNA well, which takes into account both DNA inputs for PCR and digests. Next to it is the input DNA vol, which draws from a user inputted value in the dsDNA sheet (col AP) which should be copy and pasted from col AO in thes dsDNA sheet. AO is the "Calculated input DNA vol (µL)"
- the "Calculated input DNA vol (µL)" is coded as follows, empty if the type is anneal, the settings_dPCRTemplateVolume value for PCRs if it is specified, and "<0.5 otherwise". For digests, it is the amount to digest (ng) divided by the concentration of the dna to digest (drawn from the respective tabs -- miniprep, dsDNA -- for gblock oligos, I used the settings_gOligoDonorDefaultConcentration value for concentration of all oIDs)
3. Added note to the input DNA vol(µL): Fill out the 'Input DNA vol (µL)' column in 3. Mixing and incubation of the dsDNA d sheet to show the input DNA volumes to add --> don't know if this is alerting enough though...

**Comment by evelynqi** [comment]
> dsDNA "Status" and "Queueing validity check" don't appropriately check "Type" for "digest" and handle things appropriately. Instead "digest" type is handled like a PCR, inappropriately.

It also does this; queueing validity check is good with all the digest conditions and works. Status still does not particularly like digests and thinks that the template does not exist..

**Comment by bthuronyi** [comment]
> Status still does not particularly like digests and thinks that the template does not exist..

No worries, this is for #134.

**Comment by bthuronyi** [comment]
> 3\. Added note to the input DNA vol(µL): Fill out the 'Input DNA vol (µL)' column in 3. Mixing and incubation of the dsDNA d sheet to show the input DNA volumes to add --> don't know if this is alerting enough though...

I think we only need to provide as much of an alert as is currently done for other tabs that require pasting volumes -- Assemblies and Golden Gate. If we choose to revise that messaging, we can do it for all of those tabs at the same time.

And, broadly, I think starting out assuming users will do what they're told is reasonable; we can add more guardrails against disallowed behavior (here, not filling in a required field) later.

**Comment by bthuronyi** [comment]
Let's make the "Input DNA vol (µL)" column in dsDNA d have grayed out conditional formatting for types other than "digest".

**Comment by bthuronyi** [comment]
Moved the checkbox for Input DNA vol on Asst so it's next to the volume; changed title of "template strain well" column to "Template strain well (if needed for PCRs)"

**Comment by bthuronyi** [comment]
Looks good, certainly good enough to implement in main and debug from there! Go for it!

**Comment by evelynqi** [comment]
> Let's make the "Input DNA vol (µL)" column in dsDNA d have grayed out conditional formatting for types other than "digest".

I changed it so that the input DNA vol(µL) in the asst dsDNA sheet also takes this value into account, so it is needed for PCRs as well.

**Comment by bthuronyi** [comment]
> I changed it so that the input DNA vol(µL) in the asst dsDNA sheet also takes this value into account, so it is needed for PCRs as well.

I think because this is almost meaningless / finicky to track for PCRs, we should have digests draw from it but PCRs always use the default -- is that doable to code without too much trouble? This is one situation where I'm concerned that requiring compliance in filling it in will be counterproductive because it's hard to even measure it and pasting "<0.5" will seem confusing.

**Comment by evelynqi** [comment]
Okay, yes, it's not too tricky to code.

**Comment by evelynqi** [comment]
> DONE -- queueing validity check (AJ) Takes into account multiple sources of template DNA. Gives "DNA template not appropriate for digest!" for non gblock oIDs
> https://docs.google.com/spreadsheets/d/1bzumeOTEN57T3ak3pbLISh5hERLXs2nSg6Wq2Fliesw/edit?usp=sharing

Implemented everything except this.. you seem to be working in the cells and the code I put in changed so I will wait until you are done.. (code in dsDNA AJ1284 // for non gblock oIDs)

**Comment by bthuronyi** [comment]
> > DONE -- queueing validity check (AJ) Takes into account multiple sources of template DNA. Gives "DNA template not appropriate for digest!" for non gblock oIDs
> > https://docs.google.com/spreadsheets/d/1bzumeOTEN57T3ak3pbLISh5hERLXs2nSg6Wq2Fliesw/edit?usp=sharing
> 
> Implemented everything except this.. you seem to be working in the cells and the code I put in changed so I will wait until you are done..

Haha yes sorry. I'm updating dsDNA queueing validity check. But I will fold in your code if/when it's done, just post it here. I'm now working in a copy.

**Comment by evelynqi** [comment]
I added to to the ifs to check L to see if it is a PCR to do the PCR things; and then if it is digest type. 

If it is digest type, then 

$L1286="digest",ifs(countblank(T1286,V1286,W1286,X1286,Y1286,Z1286,AA1286,AD1286,AE1286)>0,"digest conditions are missing!",
regexmatch(X1286,"^\D\d+$"),
 let(status,switch(left(X1286),
 "m",iferror(index(Minipreps_m_Status,xmatch(X1286,Minipreps_m_ID)),"error"),
 "o",iferror(index(Oligos_o_Status,xmatch(X1286,Oligos_o_ID)),"error"),
 "d",iferror(index(dsDNA_d_Status,xmatch(X1286,dsDNA_d_ID)),"error"),
 "r",iferror(index(Registry_Status,xmatch(X1286,Registry_ID)),"error"),
 "s",iferror(index(Strains_s_Status,xmatch(X1286,Strains_s_ID)),"error")
  ),
 ifs(
  status="error","Template ID not recognized!",
  left(X1286)="o", if(index(Oligos_o_dsDNA_or_ultramer?,xmatch(X1286,Oligos_o_ID))=FALSE, "DNA template not appropriate for digest!", if(or(regexmatch(status,"done"),regexmatch(status,"Complete")),"✓ No queueing errors found","Template not available yet?")), 
  or(regexmatch(status,"done"),regexmatch(status,"Complete")),"✓ No queueing errors found",
  TRUE,"Template not available yet?")),
not(isnumber(xmatch(X1286,Registry_Construct_name))),"Template not registered!",
not(regexmatch(index(Registry_Status,xmatch(X1286,Registry_Construct_name)),"Complete")),"Template not available yet?",
TRUE,"✓ No queueing errors found"))

________________________________________________________________
In context:

$L1286="PCR", ifs(countblank(Q1286,R1286,S1286,T1286,V1286)>0,"PCR conditions are missing!",
not(or(
and(iferror(search(index(Oligos_o_Sequence,xmatch(M1286,Oligos_o_ID)),AK1286),FALSE),iferror(search(DNA_REVERSE_COMPLEMENT(index(Oligos_o_Sequence,xmatch(N1286,Oligos_o_ID))),AK1286),FALSE)),
and(iferror(search(index(Oligos_o_Sequence,xmatch(N1286,Oligos_o_ID)),AK1286),FALSE),iferror(search(DNA_REVERSE_COMPLEMENT(index(Oligos_o_Sequence,xmatch(M1286,Oligos_o_ID))),AK1286),FALSE))
)),"Primer not found in fragment sequence!",
regexmatch(O1286,"^\D\d+$"),
 let(status,switch(left(O1286),
 "m",iferror(index(Minipreps_m_Status,xmatch(O1286,Minipreps_m_ID)),"error"),
 "o",iferror(index(Oligos_o_Status,xmatch(O1286,Oligos_o_ID)),"error"),
 "d",iferror(index(dsDNA_d_Status,xmatch(O1286,dsDNA_d_ID)),"error"),
 "r",iferror(index(Registry_Status,xmatch(O1286,Registry_ID)),"error"),
 "s",iferror(index(Strains_s_Status,xmatch(O1286,Strains_s_ID)),"error")
  ),
 ifs(
  status="error","Template ID not recognized!",
  or(regexmatch(status,"done"),regexmatch(status,"Complete")),"✓ No queueing errors found",
  TRUE,"Template not available yet?")),
not(isnumber(xmatch(O1286,Registry_Construct_name))),"Template not registered!",
not(regexmatch(index(Registry_Status,xmatch(O1286,Registry_Construct_name)),"Complete")),"Template not available yet?",
TRUE,"✓ No queueing errors found"),

$L1286="digest",ifs(countblank(T1286,V1286,W1286,X1286,Y1286,Z1286,AA1286,AD1286,AE1286)>0,"digest conditions are missing!",
regexmatch(X1286,"^\D\d+$"),
 let(status,switch(left(X1286),
 "m",iferror(index(Minipreps_m_Status,xmatch(X1286,Minipreps_m_ID)),"error"),
 "o",iferror(index(Oligos_o_Status,xmatch(X1286,Oligos_o_ID)),"error"),
 "d",iferror(index(dsDNA_d_Status,xmatch(X1286,dsDNA_d_ID)),"error"),
 "r",iferror(index(Registry_Status,xmatch(X1286,Registry_ID)),"error"),
 "s",iferror(index(Strains_s_Status,xmatch(X1286,Strains_s_ID)),"error")
  ),
 ifs(
  status="error","Template ID not recognized!",
  left(X1286)="o", if(index(Oligos_o_dsDNA_or_ultramer?,xmatch(X1286,Oligos_o_ID))=FALSE, "DNA template not appropriate for digest!", if(or(regexmatch(status,"done"),regexmatch(status,"Complete")),"✓ No queueing errors found","Template not available yet?")), 
  or(regexmatch(status,"done"),regexmatch(status,"Complete")),"✓ No queueing errors found",
  TRUE,"Template not available yet?")),
not(isnumber(xmatch(X1286,Registry_Construct_name))),"Template not registered!",
not(regexmatch(index(Registry_Status,xmatch(X1286,Registry_Construct_name)),"Complete")),"Template not available yet?",
TRUE,"✓ No queueing errors found"))

**Comment by bthuronyi** [comment]
Great! I've been making that code block generic and will fold in the key part:
`left(X1286)="o", if(index(Oligos_o_dsDNA_or_ultramer?,xmatch(X1286,Oligos_o_ID))=FALSE, "DNA template not appropriate for digest!", if(or(regexmatch(status,"done"),regexmatch(status,"Complete")),"✓ No queueing errors found","Template not available yet?")),
`

**Comment by bthuronyi** [comment]
Modified Status very lightly -- just add a check that oligos are only needed if type <> "digest". Modified Queueing validity check quite a bit!!

**Comment by bthuronyi** [comment]
Implemented Status message about entering volume to use for Asst: dsDNA support, as in Asst: GG

**Comment by bthuronyi** [comment]
The "Individual components" code on Asst: dsDNA wasn't moved over to Main; did so.

**Comment by bthuronyi** [comment]
Code was using a lookup table to get enzyme and buffer, but we instead specified it manually; used the manual values instead.

**Comment by bthuronyi** [comment]
Adjusted code to put digest buffer first in mix order and to properly format volumes.
