### ISSUE TITLE
Sequencing Status values need to be Settings

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#128]
Settings Status hard-codes "30" as concentration to warn about Whole-plasmid, but instead this number should be moved to Settings, e.g. settings_SequencingWholePlasmidConcWarning.

There are also a few Sequencing-related values that are not Named Ranges but need to be, and Sequencing (and all of CC) should be checked for existing references to them so we can update those to Named Ranges. Or if they are unused maybe they can be dropped, or maybe they are also hard-coded as of now.

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1YSqAdAVy6jYu_-Nbnop_aQOGMjjLDXzNKm5-Ur23Pcc/edit?usp=sharing

Settings (CS9, CT9): 
-added CS9 (Whole Plasmid Concentration Minimum) and CT9 (settings_SequencingWholePlasmidConcWarning)

Sequencing (F):
-In status, changed 30 to settings_SequencingWholePlasmidConcWarning

**Comment by evelynqi** [comment]
Regarding the second part: I think this should be on everyone's plate and everyone should be mindful of just plain text numbers in the code and we can compile a list and implement it together. Or whoever finds it can implement it.. mostly because it doesn't make sense to hunt for them (at least at this time)...

**Comment by bthuronyi** [comment]
Yup, agreed, we should do a full-CC review to find hard-coded numbers! There should be a way to make a clever REGEX to find these (and distinguish them from numbers not part of formulas, and numbers that are part of cell references).

**Comment by evelynqi** [comment]
Question on implementation.

**Comment by evelynqi** [comment]
Cut and paste values; should also take named range value with it when moving content in cells.
