### ISSUE TITLE
Check CC for hard-coded numerical values and convert these to Settings

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#130]
There are also a few Sequencing-related values that are not Named Ranges but need to be, and Sequencing (and all of CC) should be checked for existing references to them so we can update those to Named Ranges. Or if they are unused maybe they can be dropped, or maybe they are also hard-coded as of now. We should do a full-CC review to find hard-coded numbers! There should be a way to make a clever REGEX to find these (and distinguish them from numbers not part of formulas, and numbers that are part of cell references).

**Comment by santiagochrist** [comment]
It seems that we did not find much. We used the regex below, which is not exactly perfect but more or less directed us to hard-coded numbers (most were user-entered or belonging to a protocol link, etc.). This issue could be opened in the future, but there's no blaring number of violations here.

Regex:
`^=[^A-Z]*\$*\d`

Explanation:
`= // start with an equal sign (i.e., formula)`
`[^A-Z] // preceded by non-capital letters (i.e., not cell references)`
`* // any number of the above`
`\$* // any number of $ signs (i.e., may be found in a cell reference)`
`\d // any digit`
