### ISSUE TITLE
STATUS assemblies

### ISSUE THREAD

**Issue by ethanjeon** [bthuronyi/CloneCoordinate#135]
A place to gather and track all assemblies Status-related issues and changes. Part of the larger Issue #64 of auditing all Status formula logic.

**Comment by ethanjeon** [comment]
240710 

#40 playing hot potato between Evelyn B and I, also between version milestones.

Assemblies and GG statuses will be the next for our group flowchart/narrative code logic review - hopefully the resulting cleanup with illuminate similar issues as well as sweep up some other v0.95/v1.0 issues

**Comment by bthuronyi** [comment]
Status checks whether construct is registered or not, but Queueing validity check should do this instead. Current code says "construct not registered!" if construct name field is blank (should say "enter construct name!")

**Comment by bthuronyi** [comment]
> If a manual status in "What to do with this transformation?" is assigned that precludes scoring a plate -- "lost plate" or "plate discarded", maybe others -- it should override the Status in Assemblies or Golden Gate. Might be other similar logic situations too. #135 #136

**Comment by ethanjeon** [comment]
was fiddling around with whether these might be better off in queueing validity than statuses:

`countif(AJ28:AQ28,"*(don't use)*")>0,"part unavailable!",`
`countif(AJ28:AQ28,"certify queueing!")>0, "certify dID queueing!",`
`countif(P28:W28,"<>")<>countif(AJ28:AQ28,"*done*"),"wait on part",`

but led to a lot of errors, and maybe it's better to keep these in status, as they reflect more in-the-moment stuff than valid queueing?

**Comment by bthuronyi** [comment]
Yeah, all 3 of those are things that can change between queueing and "ready", so they MUST be in Status.

**Comment by ethanjeon** [comment]
At this point, code is chronological and mirrors that of Golden Gate Status

**Comment by bthuronyi** [comment]
ATM, there is a bug where large numbers of Assemblies (but not GGs) show up as "ready to transform"

**Comment by bthuronyi** [comment]
> ATM, there is a bug where large numbers of Assemblies (but not GGs) show up as "ready to transform"

Fixed; it was a column reference error (probably due to column movement) in the retransformation part of the formula. Named Ranges weren't used, so I switched to those, which incidentally prevents that kind of problem as well as making the code more readable!

**Comment by bthuronyi** [comment]
Made the same change in Golden Gate #136

**Comment by ethanjeon** [comment]
Ah

Other than that, code generally looks good, Status itself uses named ranges for all ranges pulled (besides multi-column ones, like when looking at sets of parts)

**Comment by ethanjeon** [comment]
Changed all instances of part statuses containing "(don't use)" to say "part failed!"  instead of something else like "part unavailable!"
