### ISSUE TITLE
STATUS golden gate

### ISSUE THREAD

**Issue by ethanjeon** [bthuronyi/CloneCoordinate#136]
A place to gather and track all golden gate Status-related issues and changes. Part of the larger Issue #64 of auditing all Status formula logic.

**Comment by ethanjeon** [comment]
240710

#40 playing hot potato between Evelyn B and I, also between version milestones.

Assemblies and GG statuses will be the next for our group flowchart/narrative code logic review - hopefully the resulting cleanup with illuminate similar issues as well as sweep up some other v0.95/v1.0 issues

**Comment by bthuronyi** [comment]
See #141

**Comment by bthuronyi** [comment]
> If a manual status in "What to do with this transformation?" is assigned that precludes scoring a plate -- "lost plate" or "plate discarded", maybe others -- it should override the Status in Assemblies or Golden Gate. Might be other similar logic situations too. #135 #136

**Comment by ethanjeon** [comment]
At this point, code is chronological and mirrors that of Assemblies Status

**Comment by ethanjeon** [comment]
Code generally looks good, Status itself uses named ranges for all ranges pulled (besides multi-column ones, like when looking at sets of parts)
