### ISSUE TITLE
STATUS transformations

### ISSUE THREAD

**Issue by ethanjeon** [bthuronyi/CloneCoordinate#137]
A place to gather and track all transformations Status-related issues and changes. Part of the larger Issue #64 of auditing all Status formula logic.

**Comment by ethanjeon** [comment]
If I transform something today, it will only show up as "ready to score plates" tomorrow - for all of today, the transformation sample will have the status "done" I think.  

@bthuronyi Should I add a small status like "wait until tomorrow and then score plates :)" for such transformations that are a day old?  I haven't fully mapped out all of the different Minipreps column involved in determining which transformations go on to have minipreps, but I feel like adding this status couldn't hurt even if it doesn't actually impact the CC formulas.

**Comment by ethanjeon** [comment]
added "(priority)" tags in statuses

**Comment by bthuronyi** [comment]
Yeah I think that's a great idea! I agree it's unlikely to impact anything. It would also resemble messages in Oligos and Sequencing.

**Comment by bthuronyi** [comment]
If a manual status in "What to do with this transformation?" is assigned that precludes scoring a plate -- "lost plate" or "plate discarded", maybe others -- it should override the Status in Assemblies or Golden Gate. Might be other similar logic situations too. #135 #136

**Comment by ethanjeon** [comment]
> If a manual status in "What to do with this transformation?" is assigned that precludes scoring a plate -- "lost plate" or "plate discarded", maybe others -- it should override the Status in Assemblies or Golden Gate. Might be other similar logic situations too. #135 #136

In Assemblies Status #135 , replaced
`and(BS3="",value(text(today(),"yymmdd"))-value(BR3)=0),"ready to score plates",
BS3="", "ready to score plates",`

with
`and(BS3="",not(regexmatch(index(Transformations_What_to_do_with_this,xmatch(B3,Transformations_Source_ID)),"don't use"))),if(
  value(text(today(),"yymmdd"))-value(BR3)=0,"ready to score plates","ready to score plates soon (transformed today)"),`

In Golden Gate Status #136 , replaced
`and(CQ4="",value(text(today(),"yymmdd"))-value(CP4)>0),"score plates (on Transformations)",`

with
`and(CQ4="",not(regexmatch(index(Transformations_What_to_do_with_this,xmatch(B4,Transformations_Source_ID)),"don't use"))),if(
  value(text(today(),"yymmdd"))-value(CP4)=0,"score plates (on Transformations)","score plates soon (transformed today)"),`

seems to fix some false semi-old 'ready to score plates' things of lost plates

**Comment by ethanjeon** [comment]
wait did i need to put iferrors on those ^

**Comment by ethanjeon** [comment]
ok i added iferrors (around the regexmatch into transformations, in case the aID/gID doesn't show up there)

**Comment by ethanjeon** [comment]
Here, subbed in A3 (or the row's source ID) - previously was hard-coded as 'assemblies'$B$3 for all rows, which I'm pretty sure doesn't make sense...

`
if(sum(iferror(arrayformula(value(split(textjoin(", ",TRUE,filter(Transformations_Transformed_amount,Transformations_Source_ID=A3)),", "))),0)) < settings_transformationsDefaultAmount,char(10)&"overqueued?","")
`
