### ISSUE TITLE
STATUS minipreps

### ISSUE THREAD

**Issue by ethanjeon** [bthuronyi/CloneCoordinate#138]
A place to gather and track all minipreps Status-related issues and changes. Part of the larger Issue #64 of auditing all Status formula logic.

**Comment by bthuronyi** [comment]
See #141

**Comment by bthuronyi** [comment]
Made a change to handle mID automatic verification if source = sID: now check sID Status and make sure it doesn't say "(don't use)" (which is added if someone manually flags the strain as bad), and only verify mID in that case.

**Comment by bthuronyi** [comment]
Also made this change in Minipreps_m_Verified_construct_query, since apparently you can't check verified preps from Registry using Minipreps_m_Status.

**Comment by bthuronyi** [comment]
- Added actual code to identify gel problems (condition was just set to FALSE as a placeholder) -- only checked quality and intensity, not size -- we should consider whether to add that back
    - This code is now in several places -- see whether it makes anything circular to just put a conservative version in Status and look at it from "ok to use for GG?"
- Added warning if phenotype was wrong (no warning if it might be ok)

**Comment by ethanjeon** [comment]
We're gonna implement a TON of changes today 😈 

Relevant issues: #31 #104 #141 

Then, will trim code and check for unnamed named range references, style, chronology, etc.

**Comment by bthuronyi** [comment]
Final #141 change committed; closing this!
