### ISSUE TITLE
STATUS analytical PCR

### ISSUE THREAD

**Issue by ethanjeon** [bthuronyi/CloneCoordinate#139]
A place to gather and track all analytical PCR Status-related issues and changes. Part of the larger Issue #64 of auditing all Status formula logic.

**Comment by ethanjeon** [comment]
Trimmed updated to match style of other Statuses.  Code generally works and is chronological.

**Comment by bthuronyi** [comment]
This isn't quite chronological b/c the check for "ready to set up" is after the check for "already done" -- changed that.

**Comment by bthuronyi** [comment]
Added distinct "wait" messages if oligo vs. template is not available yet
