### ISSUE TITLE
Move guidance formula from Sequencing to Asst: Sequencing

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#143]
Cell B1 of Sequencing currently has this code:

`=iferror(let(unmixed_row_count,counta(iferror(filter(B3:B,regexmatch(F3:F,"ready to mix")))),
if(unmixed_row_count>0,unmixed_row_count&" rows selected are ready to mix. "&"
"&
let(plates_template,iferror(sort(unique(arrayformula(left(ID_TO_WELL(filter(A3:A,A3:A<>"",B3:B<>"",AC3:AC="")),3))))),
if(len(plates_template)>0,"Plates needed: "&join(" ",plates_template,sort(unique(arrayformula(left(ID_TO_WELL(filter(K3:K,K3:K<>"",B3:B<>"",AC3:AC="")),3))))),""))
,"Enter sort numbers to choose rows to work on")))`

This should be moved to the header line of Asst: Sequencing in an appropriate spot and adapted so it draws from Asst: Sequencing rows instead of from Sequencing.

**Comment by santiagochrist** [comment]
Updated all references, needed to add a 'Primer (o)' column on the assistance which can be done quite easily using the other assistant tab references.
`=let(unmixed_row_count,counta(iferror(filter(A3:A,A3:A<>""),"error1")), if(unmixed_row_count>0,unmixed_row_count&" rows selected are ready to mix. "&" "& let(plates_template,iferror(sort(unique(arrayformula(left(ID_TO_WELL(filter(B3:B,B3:B<>"")),3)))),"error2"), if(len(plates_template)>0,"Plates needed: "&join(" ",plates_template,sort(unique(arrayformula(left(ID_TO_WELL(filter(M3:M,M3:M<>"",A3:A<>"",F3:F="")),3))))),"")) ,"Enter sort numbers to choose rows to work on"))`
I'll delete the 'error1' and 'error2' when implemented on the main instance of CC, but this is more for legibility than anything.

**Comment by santiagochrist** [comment]
Implemented, I have a copy of the original 'Sequencing' formula with non-asst references, but after review with you in-person it all seems good.
