### ISSUE TITLE
Consolidate, rename, and trim down "What to do with this sample?" named range dropdown options

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#145]
In Settings, there are several Named Ranges of dropdown menu options for various tabs' "What to do with this sample" columns. Most of these are full-column, which isn't necessary and is a waste of cells. The Named Range names also are often a bit outdated. To consolidate these options and use only as many columns as needed (1), there is now a column titled "What to do with this sample? options (all tabs)" and the named ranges of dropdown options should be moved below this header, in tab order, with labels. The named range names should be made consistent, e.g. settings_dWhatToDoOptions for dsDNA d.

Workflow:
- Find out what the dropdown option named range is called by going to the tab's "What to do with this sample" column and checking the Data Validation on it
- Navigate to that Named Range in the Named Ranges sidebar panel and in the Sheet
- Rename the named range if needed to make consistent
- Change the cell references of the named range so that it goes up to the existing dropdown options but no further
- Cut and paste the range to the "What to do with this sample? options (all tabs)" column, with appropriate label above; no gaps between previous range and next range's label, for clarity. Cut and paste can move these around as needed.
- While at it, make sure the dropdown options include standards:
   - Do not take any actions (hold)
   - Abandon (don't use)
   - Proceed
- Delete the column that previously contained the dropdown options, if it was in its own column

**Comment by bthuronyi** [comment]
Experiments tab also needs new options added for its "What to do with this experiment" column -- just the standard set should be ok.

**Comment by bthuronyi** [comment]
Definitely just work directly in main CC for this -- it's clear what to do, and doing it in a separate sheet then repeating the process just doubles the work

**Comment by ixf1** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-3bca517c-7fff-f61c-34c8-9a9531cf0f75"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:'Times New Roman',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">What I did:&nbsp;</span></p><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:12pt;font-family:'Times New Roman',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:12pt;font-family:'Times New Roman',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">If there isn&rsquo;t a named range in the tab itself, add one&nbsp;</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:12pt;font-family:'Times New Roman',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:12pt;font-family:'Times New Roman',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Add additional options to settings (if needed) in the respective column&nbsp;</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:12pt;font-family:'Times New Roman',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:12pt;font-family:'Times New Roman',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Change the named range to the cells themselves (must scroll through all the named ranges…)</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:12pt;font-family:'Times New Roman',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:12pt;font-family:'Times New Roman',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Cut and paste into the single column in order</span></p></li><li dir="ltr" style="list-style-type:disc;font-size:12pt;font-family:'Times New Roman',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" role="presentation"><span style="font-size:12pt;font-family:'Times New Roman',serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">For strains, added the dropdown feature</span></p></li></ul><br /><div dir="ltr" style="margin-left:0pt;" align="center">
Named range in the sheet itself | Corresponding tab | Options
-- | -- | --
Experiments_What_to_do_with_this | Experiments | Complete (manual override)Abandon (don't use)Do not take any actions (hold)ProceedQueued (manual override)
Registry_Manual_status_assignment | Registry |  
Oligos_o_Hold_from_order_query | Oligos | Change one to Do not take any actions (hold)Add Proceed
dsDNA_d_Problem | dsDNA |  
USER_u_What_to_do_with_this_u_query | Assemblies (same as Golden Gate) |  
Golden_Gate_g_What_to_do_with_this_g | Golden Gate (same as Assemblies) |  
Transformations_What_to_do_with_this | Transformations |  
Minipreps_m_What_to_do_with_this_m_query | Minipreps |  
Analytical_PCR_What_to_do_with_this_sample | Analytical PCR |  
Sequencing_What_to_do_with_this_sample | Sequencing |  
G:G was changed to:Strains_s_What_to_do_with_this_sample | Strains | Added:Do not take any actions (hold)Abandon (don't use)ProceedMade a new Named Range called “Settings_Strains_WhatToDoOptions”

</div><br /><br /><br /></b>
</body>
</html>

**Comment by ixf1** [comment]
**What I did:** 
- If there isn’t a named range in the tab itself, add one 
- Add additional options to settings (if needed) in the respective column 
- Change the named range to the cells themselves (must scroll through all the named ranges…)
- Cut and paste into the single column in order
- For strains, added the dropdown feature

**Specifically for strains:**
- G:G was changed to: Strains_s_What_to_do_with_this_sample
- Added:
  - Do not take any actions (hold)
  - Abandon (don't use)
  - Proceed
- Made a new Named Range called “Settings_Strains_WhatToDoOptions”

**For oligos:**
- Changed an option to Do not take any actions (hold) and added Add Proceed
