### ISSUE TITLE
Multi-marker constructs breaks Golden Gate g "Parts with same resistance as final construct"

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#148]
For multi-marker constructs (ex. KmR, TcR), this field could potentially look like: 
Km: part 1, part 2
Tc: part 4

This is to assist with gg queueing so users understand which donors have the same resistance marker as the construct (helps to minimize/understand template contamination).

**Comment by bthuronyi** [comment]
Changed `=` to `regexmatch` in the check against Registry Marker, which should do the trick for multi-marker constructs.

Need to see how, if at all, this is used elsewhere before changing to "Km: part 1, part 2 / Tc: part 4" approach.

**Comment by bthuronyi** [comment]
It looks like there are no longer any references to this column, which makes sense given how we redid the code to look at the Transformation instead of just what _could_ have the same resistance.

So we can def update this to be more informative.

**Comment by bthuronyi** [comment]
New v1.1 issue for updating contents -- for now, it works.
