### ISSUE TITLE
Minipreps Status / queueing validity needs to handle invalid IDs better

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#152]
Inputting a source of r439784293 (doesn't exist) gives unexpected behavior in Minipreps m Status, Plate Status and intended color. #138

**Comment by ixf1** [comment]
`=if(not(regexmatch(L3,"^[agmrs]\d+$")), "This ID is invalid!", 
  let(
    input_id, L3,
    first_char, left(input_id, 1),
    id_status, iferror(
      switch(
        first_char,
        "a", isna(xmatch(input_id, USER_u_ID)),
        "g", isna(xmatch(input_id, Golden_Gate_g_ID)),
        "m", isna(xmatch(input_id, Minipreps_m_ID)),
        "r", isna(xmatch(input_id, Registry_ID)),
        "s", isna(XMATCH(input_id, Strains_s_ID))
      ), true
    ),
    if(id_status, "This ID is not found!", "")
  )
)`


put this in queuing validity check in minipreps m after it is created.

**Comment by bthuronyi** [comment]
Implemented! While working on it I found the LET was redundant since you didn't need to reuse the variables (or they were short); rewrote that way and reformatted.
