### ISSUE TITLE
Rework Dashboard "store as strain" task based on Setting

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#153]
Currently, the Dashboard handles the "store as strain" task (number 22) based on idiosyncratic formulas. We should instead:

- Make a Setting that asks whether to show strain storage as a "ready to" task...
   - automatically for all newly verified plasmids
   - only for newly verified plasmids that are marked as "store as strain"
   - never
 - Update Minipreps m Status so it respects this setting, and interacts with What to do with this sample accordingly, showing "ready to transform for strain storage"
 - Add a Minipreps "What to do with this sample" dropdown option that has the Verified heart but doesn't say "store as strain" in it; differentiate between this and the (store as strain) Verified option in Status
 - Change the Dashboard so that, based on the Setting, it EITHER looks for the "ready to transform for strain storage" status, or uses the existing code, or just displays "(off)" or something

**Comment by bthuronyi** [comment]
#138

**Comment by bthuronyi** [comment]
We need a way to manually set "store as strain" to be a high-priority task... maybe doing it with an mID "what to do with this" option is good enough. Currently, completed constructs ignore their priority designation (prob appropriately) so setting the Registry priority flag doesn't prioritize strain storage even if the Status of the mID were to change.

**Comment by santiagochrist** [comment]
Status Code:
-
```
...
   ifs(
       iferror(and(left(K3)="s",index(Strains_s_Storage_strain?,ID_TO_INDEX(K3)),not(regexmatch(H3,"(don't use)"))),FALSE),char(10)&"♥ verified",
       iferror(left(K3)="r",FALSE), char(10)&"♥ verified",
       iferror(regexmatch(H3,"♥"),FALSE), 
          
              iferror(if(regexmatch(BH3,"All parts verified present"),char(10)&"♥ verified", char(10)&"♥ verified"&char(10)&"sequencing data missing?"),"")& 
              ifs(
                  and(regexmatch(settings_mReadyFlag,"auto"),$BL3="",$BJ3=FALSE), char(10)&"ready to transform for strain storage",
                  and(regexmatch(settings_mReadyFlag,"only"),$BL3="",$BJ3=FALSE), if(NOT(regexmatch(H3,"(store this prep)")),"",char(10)&"ready to transform for strain storage"),
                  TRUE,""
                 ),
       TRUE,""
     )&
 ...
```
Effectively removes the need for Column BM "Needs to be stored?" to exist.
Works as intended right now and should be modular, so should ask @ethanjeon where in the Status code it should go (if different from where I currently have it at in between "gel problem" and "ready to inoculate for storage."

Dashboard Code:
-
`=counta(iferror(filter(Minipreps_m_Status,regexmatch(Minipreps_m_Status,"ready to transform for strain storage"))))`
After making an outcome matrix and adjusting the Status code's logic, the counts for "auto" and "only store as strain" seem to be working well; the "never" option also works in that it returns a count of 0.

The "ready to transform for strain storage" will actually go in cell `F25`, and so the dashboard code will be adjusted to reference F25 instead of hard-coded text.

Settings Code: 
-
CJ9: `Strain storage options:`
CK9 (Named range `settings_mReadyFlag` containing a dropdown): 
```
automatically for all newly verified plasmids
only for newly verified plasmids that are marked as "store as strain"
never
```

**Comment by santiagochrist** [comment]
Priority:
-
Added a `Fully sequence-verified (store this prep) ♥ (priority)` option in the "What to do with this sample?" column dropdown. 

Adjusted the "Priority?" code to make it effective:
`=iferror(or(and(B220<>"",iferror(regexmatch(Registry_Priority_flagged_IDs,B220&","))),regexmatch(H220,"(priority)")))`

**Comment by santiagochrist** [comment]
#138 
```
...
   ifs(
       iferror(and(left(K3)="s",index(Strains_s_Storage_strain?,ID_TO_INDEX(K3)),not(regexmatch(H3,"(don't use)"))),FALSE),char(10)&"♥ verified",
       iferror(left(K3)="r",FALSE), char(10)&"♥ verified",
       iferror(regexmatch(H3,"♥"),FALSE), 
          
              iferror(if(regexmatch(BH3,"All parts verified present"),char(10)&"♥ verified", char(10)&"♥ verified"&char(10)&"sequencing data missing?"),"")& 
              ifs(
                  and(regexmatch(settings_mReadyFlag,"auto"),$BL3="",$BJ3=FALSE), char(10)&"ready to transform for strain storage",
                  and(regexmatch(settings_mReadyFlag,"only"),$BL3="",$BJ3=FALSE), if(NOT(regexmatch(H3,"(store this prep)")),"",char(10)&"ready to transform for strain storage"),
                  TRUE,""
                 ),
       TRUE,""
     )&
 ...
```
Ethan: I described above where the code is currently placed, just need to be sure that it is in the right place in Status.
