### ISSUE TITLE
Asst dsDNA sheet doesn't handle different additives (PCR conditions) when premixing is turned off in settings.

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#158]
They should show up on the additional component(s) cols and rows... For example, PCR enhancer (betaine, DMSO, DTT, BSA) and PCR enhancer + SSB (with volumes) should show up in the Additional component(s) cells

**Comment by evelynqi** [comment]
This is due to coding bug "Is premixing preferred for this combination?" in Asst dsDNA sheet. 

The **=if(or(CF3="",settings_dPCRPremixAllowed?=FALSE),"",**
(counta(index(settings_dPCRPolymeraseComponentsTable,match($CG3,settings_dPCRPolymeraseList,0)))+counta(index(settings_dPCRVariationComponentsTable,match($CH3,settings_dPCRVariationList,0))))/2+CF3
<=
(counta(index(settings_dPCRPolymeraseComponentsTable,match($CG3,settings_dPCRPolymeraseList,0)))+counta(index(settings_dPCRVariationComponentsTable,match($CH3,settings_dPCRVariationList,0))))/2*CF3
+settings_dPCRPremixBias
)

should be 

=**if(or(CF3="",settings_dPCRPremixAllowed?=FALSE),FALSE,**
(counta(index(settings_dPCRPolymeraseComponentsTable,match($CG3,settings_dPCRPolymeraseList,0)))+counta(index(settings_dPCRVariationComponentsTable,match($CH3,settings_dPCRVariationList,0))))/2+CF3
<=
(counta(index(settings_dPCRPolymeraseComponentsTable,match($CG3,settings_dPCRPolymeraseList,0)))+counta(index(settings_dPCRVariationComponentsTable,match($CH3,settings_dPCRVariationList,0))))/2*CF3
+settings_dPCRPremixBias
)

When premixing is turned off, premixing col should return FALSE instead of "". It works in this edited sheet: https://docs.google.com/spreadsheets/d/1bzumeOTEN57T3ak3pbLISh5hERLXs2nSg6Wq2Fliesw/edit?usp=sharing but not in the main sheet.

**Comment by bthuronyi** [comment]
Nice! I've made the change in main CC. I don't understand why this happened exactly because the truth-value of "" in Sheets is FALSE, so typically you don't run into problems with using it in place of FALSE. But ""=FALSE returns FALSE, so maybe we used that more stringent check or some other thing happened. No problem either way.
