### ISSUE TITLE
Warn if USER / anneal junctions are reverse complements of each other

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#161]
pBWT101 has USER and anneal junctions that are reverse complements of each other, so that it seems to me the anneal can (and did!) insert in either orientation. At some level, maybe even as far back as the dID that was generated using USER primers containing reverse complementary junctions, there should be warnings about this. It can be fine but it's a design that should be avoided in general because if the part goes in backwards people may not notice that and will think there's just some random insert.

**Comment by bthuronyi** [comment]
See maps for pBWT101 (original design) vs pBWT140 (annealed oligos insert in reverse orientation)

**Comment by shen2333333** [comment]
I couldn't find pBWT140

**Comment by shen2333333** [comment]
![image](https://github.com/user-attachments/assets/f80b8242-1037-439f-8a20-d4a7609195f9)
So AgacgacT anneal junction is the issue...

**Comment by shen2333333** [comment]
For the specific anneal dna, this does tell the story
![image](https://github.com/user-attachments/assets/e2bcef27-eda8-40e5-815e-99721b73e550)

**Comment by shen2333333** [comment]
![image](https://github.com/user-attachments/assets/96d5377c-d6bc-4946-a4e1-62d5d499f991)

**Comment by shen2333333** [comment]
So if I'm understanding correctly, we don't want the junctions, the A........T (8-12 bases) to be reverse complement to be each other because then we can get inserts joined in reverse, which is what we don't want. And give warning to that

**Comment by bthuronyi** [comment]
> I couldn't find pBWT140

Hmm maybe I accidentally made it in a folder not shared with the lab? I'll follow up

**Comment by bthuronyi** [comment]
> So if I'm understanding correctly, we don't want the junctions, the A........T (8-12 bases) to be reverse complement to be each other because then we can get inserts joined in reverse, which is what we don't want. And give warning to that

Yes, correct - and actually whatever the lengths of the junctions are, we should warn if they are perfect reverse complement.

**Comment by bthuronyi** [comment]
> > I couldn't find pBWT140
> 
> Hmm maybe I accidentally made it in a folder not shared with the lab? I'll follow up

That was indeed the case. Fixed now.

**Comment by shen2333333** [comment]
![image](https://github.com/user-attachments/assets/7cc626cc-ef6f-410f-bb6b-75d43782f420)
Ah, that's it.

**Comment by bthuronyi** [comment]
> Ah, that's it.

Yep. Had a real interesting time slowly realizing what had happened from the sequencing!

**Comment by shen2333333** [comment]
Here's some ideas

https://docs.google.com/spreadsheets/d/1lhkEwbCgvcBTcsMinydFHJqrcuTSCYxowrtGUPQZmyY/edit?gid=25148367#gid=25148367
1. I take advantage column Right junction sequence (5'>3', only 3' overhangs currently supported) and Left junction sequence (5'>3', only 3' overhangs currently supported)
![image](https://github.com/user-attachments/assets/1f0665ce-fe71-4046-8310-b44ae5616e38)
For USER, I could use this formula to warn, =if(DNA_REVERSE_COMPLEMENT(AJ1186)=AK1186,"Warning: junctions are reverse complement",""); very useful for named function finding reverse complement

For anneal, I could use this formula 
![image](https://github.com/user-attachments/assets/e605944e-acbe-4034-9b6d-babbea36b7d6)
=LET(
    underscore_pos, FIND("_", AJ1205),
    first_part, LEFT(AJ1205, underscore_pos - 1),
    second_part, MID(AJ1205, underscore_pos + 1, LEN(AJ1205) - underscore_pos),
    IF(ISNUMBER(underscore_pos),
        IF(first_part = second_part, "Warning: junctions are reverse complement", ""),
        ""
    )
)


But I think to actually warn user, somehow it needs to be incorporated into the giant "Queueing validity check"? which I'm not quite sure how to approach.

**Comment by bthuronyi** [comment]
Implemented along the lines you laid out. Had to change the junction determination formulas so they are active before Certify correct queued is checked off; also updated them to more modern coding practices.

**Comment by bthuronyi** [comment]
As so often happens when we introduce new automated warnings, *24 different dsDNA fragments* were queued in the past that have reverse-complementary junctions, affecting 13 constructs...
