### ISSUE TITLE
Sweep through all green/blue columns and make sure Named Range exists

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#182]
Sweep through all green/blue columns and make sure Named Range exists

**Comment by santiagochrist** [comment]
- [x] Experiments:
- [x] Status needed to consider ID(s) to be ready to use
- [x] Registry:
- [x] Compatibility group/origin family
- [x] Oligos:
- [x] Secondary structure at 63°C
- [x] Certify correctly queued
- [x] dsDNA d:
- [x] Sort #
- [x] Digest type
- [x] Amount to digest (ng)
- [x] Enzyme vol (µL)
- [x] Enzyme 2 vol (µL)
- [x] Buffer
- [x] Assemblies a:
- [x] Note: a lot of named ranges still use the old "USER_x_y_Z" format, may want to change that.
- [ ] 
- [x] Sort #
- [x] Golden Gate g:
- [x] Sort #
- [x] Transformations:
- [x] Sort #
- [x] Analytical PCR priority
- [x] Recovery media
- [x] Growth temperature
- [x] Actual growth conditions
- [x] Minipreps:
- [x] Sort #
- [x] Analytical PCR priority
- [x] Certify correctly queued
- [x] Culture media
- [x] Culture antibiotic
- [x] Actual growth conditions
- [x] Analytical PCR:
- [x] Sort #
- [x] Sequencing:
- [x] Sort #
- [x] Certify correctly queued
- [x] Strains s:
- [x] Specific growth conditions
- [x] Certify correctly queued

**Comment by bthuronyi** [comment]
Great! I will get these named momentarily. The Sort # fields are the one exception where they are both user data and also considered temporary so we don't copy them from instance to instance. Though I guess there is not a strong justification for that so maybe I will just name them too to be consistent.

**Comment by bthuronyi** [comment]
Sorry I messed up the comment formatting and there is apparently no straight-up "revert edit" function...

**Comment by bthuronyi** [comment]
> Note: a lot of named ranges still use the old "USER_x_y_Z" format, may want to change that.

Yeah, it's on the list, but changing any named range names creates issues at the moment, so we need a script to sort through it #82 #171

**Comment by bthuronyi** [comment]
Can you also look at Settings and admin? It's much more of a mess in there, but the blue/green highlight scheme still holds true, for individual cells typically or sometimes ranges or columns.

**Comment by santiagochrist** [comment]
> Sorry I messed up the comment formatting and there is apparently no straight-up "revert edit" function...

I thought there'd be an edit history like when you include code, but I guess not...

**Comment by bthuronyi** [comment]
> I thought there'd be an edit history like when you include code, but I guess not...

It does provide an edit history but not in the correct markdown and only as a diff -- so you can't just straight up copy and paste back an old version. Apparently a known Github issue, not fixed/implemented yet.

**Comment by santiagochrist** [comment]
I may have been somewhat overkill with this list, but I think I spotted almost everything that raised flags to me.

Settings & admin:
-

- [ ] - Column I:K (none of these values): Dashboard info, although this pulls from dashboard and outputs it onto settings, I thought it'd maybe be the other way around but oh well just thought I'd note it.
- [x] - Column L: Registry: Project list dropdown (do we want to named range this and output the array??)
- [x] - Column N: Registry: Antibiotics table (is this purely for human reference and unused?)
- [x] - Column X: dsDNA thermocycler block dropdown options
- [x] - Column AA:AZ: Nothing in here is named, is this all just human reference or do we have a really ugly, non- named range references?
- [x] - Column BC:BD: QC Agarose gel ladders
- [x] - BF34:BF38: QC Priority list, in priority from low to high
- [x] - BK4:BL8: Assembly type this enzyme mix recipe is for | Recipe name to show in dropdown in Assemblies a
- [x] - Column BN:BW: Assembly components table
- [x] - Column CA:CB: Transformation procedures (for dropdown menu) | Transformations Competent cell batches
- [x] - Column CL:CN: Sequencing stuff (titles too long sorry)
- [x] - CP7:C13: Plasmid, miniprep volume stuff

**Comment by bthuronyi** [comment]
> * Column I:K (none of these values): Dashboard info, although this pulls from dashboard and outputs it onto settings, I thought it'd maybe be the other way around but oh well just thought I'd note it.

Yeah, this is a bit of a mess and I need to back up and rethink how it's gonna work -- but, noted!

**Comment by bthuronyi** [comment]
> * [x]  - Column L: Registry: Project list dropdown (do we want to named range this and output the array??)
> *

This is actually a named range that starts in row 2; it's ok as-is. I adjusted it to go to the bottom row.

**Comment by bthuronyi** [comment]
> * [ ]  - Column N: Registry: Antibiotics table (is this purely for human reference and unused?)
> *

Also a not-full-column Named Range

**Comment by bthuronyi** [comment]
> * [x]  - Column X: dsDNA thermocycler block dropdown options
> *

Didn't go to row 200; fixed

**Comment by bthuronyi** [comment]
> * - Column AA:AZ: Nothing in here is named, is this all just human reference or do we have a really ugly, non- named range references?

Non-full-column Named Ranges

**Comment by bthuronyi** [comment]
> * [ ]  - Column BC:BD: QC Agarose gel ladders
> *

Non-full-column Named Ranges

**Comment by bthuronyi** [comment]
> * CP7:C13: Plasmid, miniprep volume stuff

This was quite a mess -- some cells were unused and the equivalent value hardcoded in! All sorted now.

**Comment by bthuronyi** [comment]
> * [ ]  - Column I:K (none of these values): Dashboard info, although this pulls from dashboard and outputs it onto settings, I thought it'd maybe be the other way around but oh well just thought I'd note it.
> *

Remaining problem

**Comment by bthuronyi** [comment]
Moved remaining task to new issue.
