### ISSUE TITLE
Registry status could handle constructs with the same construct name better

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#184]
Constructs need to only be added to the registry once, so each construct name should be unique. I feel like once a construct name is entered, if it has the same name as a previous construct, the status should automatically reflect that. Instead, the status saids "Finish registering" until all of the components are added and the queueing is certified as correctly registered. After certifying correctly registered, the status changes to reflect the other construct's status, so it can immediately become "complete" or "queued" from the other construct with the same name. I think this could be confusing. I think we should add a line of code that checks whether the construct name already exists right after the user enters it. 

https://docs.google.com/spreadsheets/d/1cFaa-ti10-2hyFhcT3fXNCT8jmujyg62V4yv4dg6tKg/edit?usp=sharing
Registry r1297

**Comment by bthuronyi** [comment]
Agreed, this is important to fix. I would say that as soon as the construct name field is filled in and is identical to a construct name above (and we might also add a warning if the construct name is a substring of a construct name above), Queueing validity check should give an error message.

**Comment by bthuronyi** [comment]
Added duplicate checking to Queueing validity check
