### ISSUE TITLE
Asst: dsDNA input DNA template name is incorrect

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#186]
Right now, it says "Input DNA vol for digest (µL)" but it is used for PCRs as well. The way that it is coded is to get the user inputted value for DNA digest but be "<0.5µL" for PCRs. 

Also, "<0.5µL" for PCR template DNA vol is hardcoded. Maybe we should have a setting for users to input their own value.. though it is a PCR so it always needs very little template.. what if people just don't like seeing "<0.5"...

**Comment by bthuronyi** [comment]
Changed column title and language for PCRs. I think there's no great option for getting around the <0.5 thing, but I hopefully made it more appealing looking.
