### ISSUE TITLE
Queueing validity check in Assemblies...maybe has a bug..?? 

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#187]
a958 in assemblies gives "Junction error: check parts!" for "Queueing validity check" for a one part assembly. It may just be that the part is queued incorrectly and this is not a problem for queueing validity check but I can't figure out how to check because I can't find the pMC0star_A_03 map on benchling...

**Comment by bthuronyi** [comment]
Yeah, could be! The map is under "pMC0*_A_03" -- originally we used MATCH and it couldn't deal with *'s in names so we renamed all the constructs in our Registry but not on Benchling...

**Comment by evelynqi** [comment]
Not a bug.
