### ISSUE TITLE
asst: assemblies premix gives lots of #N/A messages

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#189]
https://docs.google.com/spreadsheets/d/1cFaa-ti10-2hyFhcT3fXNCT8jmujyg62V4yv4dg6tKg/edit?usp=sharing
Asst: assemblies

**Comment by evelynqi** [comment]
There is a REF error in BI (Asst: Assemblies) because it refers to settings_uPremixFractions and settings_uAssemblyTypes but these are rearranged differently in settings now. I need a little help fixing this.

`=if(BH3,
AX3*index(settings_uPremixFractions,xmatch(AY3,settings_uAssemblyTypes))
,"")`

**Comment by evelynqi** [comment]
OLD:
<img width="880" alt="old" src="https://github.com/user-attachments/assets/4e644bf1-bb82-47f5-b23a-ebfe57e5f4b7">

NEW:
<img width="438" alt="new" src="https://github.com/user-attachments/assets/37c93da8-ebb9-4295-a387-c65d85f5cf6b">

**Comment by evelynqi** [comment]
We are trying to pull out the "0.5" value for each assembly type.

**Comment by bthuronyi** [comment]
Ah, shoot, yeah, this is my fault -- I rearranged these but didn't fully deal with the consequences apparently. Let me look into it.

**Comment by bthuronyi** [comment]
Because of the rearrangement I did, the assembly types just need to be hard-coded, so I did that via SWITCH referencing the appropriate named ranges.
