### ISSUE TITLE
Settings_analytical_PCR_NoAbandonedConstructs -- setting doesn't work.

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#192]
Settings_analytical_PCR_NoAbandonedConstructs is a setting for "If a construct is marked abandoned in the Registry, never mark analytical PCRs related to that construct as ready".. I may be wrong about this but in theory then, if it is unchecked, a construct can be abandoned in the registry and be marked ready for analytical PCR...I believe the code in transformations makes sure that no  construct will be marked ready for analytical PCRs when a construct is abandoned in the Registry.

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1cFaa-ti10-2hyFhcT3fXNCT8jmujyg62V4yv4dg6tKg/edit?usp=sharing
Transformations D1481

**Comment by bthuronyi** [comment]
Not a bug: intended use of the setting is to affect Analytical PCR Status, not Transformation or Minipreps m Status, and the Analytical PCR Status code looks straightforward for that. The question of how/when to stop work on Abandoned constructs is a bigger one than this setting.
