### ISSUE TITLE
Rename setting description for requiring colony analytical PCRs to be queued and done before being marked for minipreps and for requiring miniprep analytical PCRs to be queued and done before being marked for sequencing

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#193]
Require analytical PCRs to be queued and completed before gIDs are marked "ready to queue miniprep"?
--
Require analytical PCRs to be queued and completed before gID-derived minipreps are marked "ready to queue sequencing"?
Require analytical PCRs to be queued and completed before aIDs are marked "ready to queue miniprep"?
Require analytical PCRs to be queued and completed before aID-derived minipreps are marked "ready to queue sequencing"?

The way that these settings work is that it is conditional on the priority flags. So if "Require analytical PCRs to be queued and completed before gIDs are marked "ready to queue miniprep"?" is checked, we require analytical PCRs to be queued and done ONLY if the priority flag is above what we designate it to be on the "Designate analytical PCR as a Dashboard task for gID-derived transformations when the sample "analytical PCR priority" column is set to:" setting. This may not be that clear. We may want to implement a message after the options or we can change the text to say something like "Require **flagged** analytical PCRs to be queued and completed before gIDs are marked "ready to queue miniprep"?"

May not be necessary but it would make things clearer

**Comment by bthuronyi** [comment]
How do these sound? @evelynqi 

For gID transformations: If analytical PCR is called for based on the priority levels set below (gID status shows "ready to queue analytical PCR"), require at least 1 analytical PCR to be queued and completed before the gID is marked "ready to queue miniprep"?

For mIDs derived from gIDs: If analytical PCR is called for based on the priority levels set below (mID status shows "ready to queue analytical PCR"), require at least 1 analytical PCR to be queued and completed before the mID is marked "ready to queue sequencing"?

(then aID versions below those)
