### ISSUE TITLE
Not a bug but we may want "Analytical PCR overall outcome" in minipreps to have an "all didn't work" outcome. 

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#196]
So far, the options are "yes, done", "some didn't work", "ambiguous", and "all worked".

The next column over is individual outcomes though so maybe this is not necessary. You can tell when all the analytical PCRs didn't work by their individual outcomes.

**Comment by bthuronyi** [comment]
Implemented, but the code in these columns is pretty hacky and could use revision eventually.
