### ISSUE TITLE
Miniprep status doesn't change to "ready to sequence" even when it is ready to sequence when the  "Require analytical PCRs to be queued and completed before gID-derived minipreps are marked "ready to queue sequencing"?" option is on.

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#198]
Settings_analytical_PCR_gIDRequireQueueingAfterMiniprep is the checkbox for "Require analytical PCRs to be queued and completed before gID-derived minipreps are marked "ready to queue sequencing"?". When it is checked, even when the miniprep's analytical PCR is queued and completed, it never makes it to "ready to sequence". Instead, it becomes "done". 

I didn't test it but I'm assuming this is a problem for aID-derived minipreps as well -- "Require analytical PCRs to be queued and completed before aID-derived minipreps are marked "ready to queue sequencing"?"

**Comment by ethanjeon** [comment]
(checkbox no longer exists)
