### ISSUE TITLE
No code uses settings_SequencingRequireQC?

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#199]
I don't think any code uses settings_SequencingRequireQC? but I also don't think we need it since we have individual settings for each QC operation.. 

We have:
- settings_SequencingRequireQuant?
- settings_SequencingRequireGel?
- settings_SequencingRequireAnalyticalPCR?
- Settings_analytical_PCR_gIDRequireQueueingAfterMiniprep
- Settings_analytical_PCR_aIDRequireQueueingAfterMiniprep

also maybe we rename the last two listed here to settings_gIDMiniprepSequencingRequireAnalyticalPCR? and settings_aIDMiniprepSequencingRequireAnalyticalPCR?

**Comment by bthuronyi** [comment]
Agreed -- settings_SequencingRequireQC? is probably a holdover from an earlier implementation. I'll remove it. Please implement the name changes, I agree with them and they are very very unlikely to be referenced in accessory sheets as of now.

**Comment by bthuronyi** [comment]
Are the last 2 settings redundant with what we implemented for analytical PCR under "QC and analytical PCR settings"?

**Comment by bthuronyi** [comment]
Wait, no, it's supposed to refer to dIDs. I'll implement it instead.

**Comment by bthuronyi** [comment]
Implemented check in Sequencing Status -- if source is a dID and the setting is checked, look for "gel" or "quant" in its Status, and if found, instead of "ready to mix" show "wait on source QC"

**Comment by evelynqi** [comment]
Implemented new names.
