### ISSUE TITLE
"What to do with this mID?" in Sequencing should be a required field (green header instead of blue?)

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#200]
Otherwise, the nothing really happens to the prep...

**Comment by evelynqi** [comment]
Note from B: Change "Sequencing <> Minipreps "What to do with this?" integration" in Minipreps sheet to ignore "Proceed" and possibly something else...

**Comment by bthuronyi** [comment]
Making the integration column ignore "proceed" from Minipreps or Sequencing seems to have sorted this out nicely.
