### ISSUE TITLE
"ready to inoculate for storage" is appended to the status instead of replacing "ready to transform for strain storage". also even after inoculation, "ready to transform for strain storage" message stays in status

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#202]
Example message: 

"done
ready to prep gel sample
♥ verified (from Sequencing)
**ready to transform for strain storage
ready to inoculate for storage**"

When it is ready to be stored as a strain, it should say "ready to transform for strain storage" and once it has been transformed, it should say " ready to inoculate for storage".

**Comment by bthuronyi** [comment]
"ready to store" message also appears in Strains inappropriately

**Comment by ethanjeon** [comment]
Miniprep Status - simply added an explicit check for blank 'date transformed' column
`
and(regexmatch(settings_mAutomaticReadyToTransformOption,"auto"),$BQ3="",$BO3=FALSE,BR3="yes",BS3=""), char(10)&"ready to transform for strain storage"
`
