### ISSUE TITLE
Remove black borders in all tabs

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#208]
Many tabs still have black border formats, often patchy, between columns. They tend to get removed when someone pastes into a cell. With the new color border highlight at the top, these are basically redundant and are hard to maintain. We should remove all of them. The top rows are a little finicky because you need to preserve the colored border.

![image](https://github.com/user-attachments/assets/50fefe7d-0d42-4d76-883d-7737202733c0)

Copying and pasting-as-format nearby cells can be helpful for this.

![image](https://github.com/user-attachments/assets/e44133de-0b09-437f-9bf0-8e9dfdab09ca)

**Comment by bthuronyi** [comment]
There are still borders on Assemblies a

**Comment by bthuronyi** [comment]
And Transformations

**Comment by santiagochrist** [comment]
Oh no I was working on a copy :(

**Comment by bthuronyi** [comment]
Good news is you can Copy > Paste format only from a different spreadsheet

**Comment by santiagochrist** [comment]
There were also some lines leftover on dsDNA, Registry, and Golden Gate. Yeah, I definitely dropped the ball on this one haha.

LMK @bthuronyi

**Comment by bthuronyi** [comment]
We'll just clear out the rest as we run into them! Thanks
