### ISSUE TITLE
All Asst volumes should be wrapped in FORMAT_FOR_PIPETTING

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#210]
I used to think that referencing a formatted number cell would maintain the format, but usually this is not the case. So Asst sheets commonly show volumes with inappropriate decimal places. I wrote the custom function FORMAT_FOR_PIPETTING to deal with this, and it needs to be implemented across Asst: tabs.

It's ok to put it on the outside of the functions, for convenience, since it returns "" when the input is "".

`=FORMAT_FOR_PIPETTING(iferror(if(A3="","",if(regexmatch($H$1,"Premix enabled"),sum($BJ$3:$BJ),"")), ""))`

**Comment by santiagochrist** [comment]
Done, I applied it to every assistant tab column that had a "µL" except for concentrations (ng/µL) since I don't think we pipette concentrations... @bthuronyi

**Comment by bthuronyi** [comment]
Modified FORMAT_FOR_PIPETTING so it handles "" input better, returning "" instead of "0.00" or similar. (Thought it did this before but it didn't!)

`=if(vol="","",to_text(ifs(vol<2,text(vol,"0.000"),vol<20,text(vol,"0.00"),vol<200,text(vol,"0.0"),TRUE,text(vol,"0"))))`
