### ISSUE TITLE
"Missing data" in dsDNA d Status appears unexpectedly

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#214]
When queueing a new PCR, dsDNA d Status shows "missing data?" when it seems like all fields are filled in so far left-to-right -- see row 1288

**Comment by bthuronyi** [comment]
Copy with bug showing:
https://docs.google.com/spreadsheets/d/1pQfp0ZuoxBA8bZuGAeSeGxdMgK_6f6cpEj2aBF7_F4o/edit?gid=1540456475#gid=1540456475

**Comment by santiagochrist** [comment]
Checkboxes that have not been checked off are marked as "FALSE" in Sheets, so it counts as an "input" into the join expression and triggers the regexmatch.
<img width="970" alt="Screenshot 2024-07-30 at 9 30 07 AM" src="https://github.com/user-attachments/assets/1eae5f84-05bc-420b-88ae-2e0f2997fa1f">

**Comment by santiagochrist** [comment]
<img width="492" alt="Screenshot 2024-07-30 at 10 10 09 AM" src="https://github.com/user-attachments/assets/81ae3c6e-a51c-46bc-9c5b-731e80bd1a47">

**Comment by santiagochrist** [comment]
Turns out there is a way to do this! We can leave the checkbox format while still having a blank value in the cell (as opposed to unchecked being false). My suspicion is that we took a non-empty, unchecked box containing "FALSE" and copied it all the way down, as opposed to an empty, unchecked box containing "".

**Comment by santiagochrist** [comment]
I have gone ahead and pasted empty, unchecked boxes in all relevant sheets (one that popped up pretty often was the "certify queueing" box). I was initially worried that not having a default `FALSE` might ruin things like queueing validity checks, but I think that nothing actually uses the `FALSE` condition. Also, users are prompted to check the box before moving on anyway and that will assign a TRUE value, so at that point users are very likely to have inputted data correctly to make the "Missing data?` condition trigger correctly. @bthuronyi

**Comment by bthuronyi** [comment]
Looks good! Checkbox data validation WITHOUT a value was new to me.
