### ISSUE TITLE
dsDNA d, Sequencing and Analytical PCR should check for Oligos status has (don't use)

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#215]
You can now Abandon an oligo but sheets that pull it don't seem to check its status, but should.

**Comment by ethanjeon** [comment]
dsDNA Status and Queueing Validity
`
iferror(regexmatch(index(Oligos_o_Status,xmatch(M3,Oligos_o_ID)),"don't use"),FALSE),"oligo 1 is lost/abandoned!",
iferror(regexmatch(index(Oligos_o_Status,xmatch(N3,Oligos_o_ID)),"don't use"),FALSE),"oligo 2 is lost/abandoned!",
`

Sequencing Status and Queueing Validity
`
iferror(regexmatch(index(Oligos_o_Status,xmatch(L3,Oligos_o_ID)),"don't use"),FALSE),"primer is lost/abandoned!",
`

Analytical PCR Status and Queueing Validity
`
iferror(regexmatch(index(Oligos_o_Status,xmatch(R3,Oligos_o_ID)),"don't use"),FALSE),"forward oligo is lost/abandoned!",
iferror(regexmatch(index(Oligos_o_Status,xmatch(S3,Oligos_o_ID)),"don't use"),FALSE),"reverse oligo is lost/abandoned!",
`

text wrapping looks a bit off on some parts of Analytical PCR...
