### ISSUE TITLE
Merge "Queued for dsDNA?" into Oligos Status

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#216]
Also remove conditional formatting on "Sequencing or analysis primer?" at the same time. Append ? message to Status if unqueued.

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1cFaa-ti10-2hyFhcT3fXNCT8jmujyg62V4yv4dg6tKg/edit?usp=sharing

Oligos -- Status
`&if(X3="queue me!","?","")`

Removed conditional formatting: 
This is the code that I removed:
`=and(regexmatch(X3,"queue"),N3<>"")`


Just some reference code//for learning//ignore for this implementation
`&
if(A3="","",if(not(or(isnumber(xmatch(B3,dsDNA_d_Oligo_1)),isnumber(xmatch(B3,dsDNA_d_Oligo_2)))),char(10)&"Queued for dsDNA?",""))`

**Comment by bthuronyi** [comment]
I was thinking actually merge the code from column X into Status. I went ahead and implemented that directly in main based on your example.
