### ISSUE TITLE
Assemblies a Status shows "ran out!" prematurely

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#217]
See row 961: message is "ran out!" when only serial # and construct name are filled in

**Comment by bthuronyi** [comment]
https://docs.google.com/spreadsheets/d/1a80R0eiw9mi_V9zMV7glKFoNniIwn_VId1iu5sHG9fg/edit?gid=1540456475#gid=1540456475

**Comment by santiagochrist** [comment]
I got a `poop4` output, so something must be going on with this segment:
```
if(or(regexmatch(output,"poop3"),regexmatch(output,"abandoned")),output,output&if(sum(iferror(arrayformula(value(split(textjoin(", ",TRUE,filter(Transformations_Transformed_amount,Transformations_Source_ID=B961)),", "))),0))>=N961,if(A961="","",char(10)&"poop4"),"")))
```

**Comment by santiagochrist** [comment]
It seems that this line is evaluating to `TRUE`:

`sum(iferror(arrayformula(value(split(textjoin(", ",TRUE,filter(Transformations_Transformed_amount,Transformations_Source_ID=B961)),", "))),0))>=N961`

**Comment by santiagochrist** [comment]
This filter has no match, which btw we can just index/xmatch to conserve resources since there is one criterion in the filter:
`filter(Transformations_Transformed_amount,Transformations_Source_ID=B961)`

Which, if there is no match, the iferror returns some kind of remaining volume as 0 uL and compares it against the scale (uL) we use for the assembly.

**Comment by santiagochrist** [comment]
Also, since the snippet is concatenated, I think it always runs despite not having entered any value for N961. A simple solution would just be to make sure that N691 is actually entered before doing anything. Notice the `and`:

```
if(
and(sum(iferror(arrayformula(value(split(textjoin(", ",TRUE,filter(Transformations_Transformed_amount,Transformations_Source_ID=B961)),", "))),0))>=N961,
N961<>""),
if(A961="","",char(10)&"ran out!"),"")))
```

**Comment by bthuronyi** [comment]
> This filter has no match, which btw we can just index/xmatch to conserve resources since there is one criterion in the filter:
> `filter(Transformations_Transformed_amount,Transformations_Source_ID=B961)`

True in general, but only when the lookup is unique -- here, there can be >1 transformation per unique source ID, so you need FILTER even with 1 criterion.

**Comment by bthuronyi** [comment]
> A simple solution would just be to make sure that N691 is actually entered before doing anything. Notice the `and`:

Looks good to me, I added to Main under both Assemblies and GGs.
