### ISSUE TITLE
Support "colors of templates/parts with same marker" info

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#218]
Would want to know what colors the other parts with the same marker as the final constructs are for choosing parts to use. Would want this on Assemblies and Golden Gate for queueing and Transformations for plate scoring. Could use similar code to "constructs with same marker".

**Comment by evelynqi** [comment]
Assemblies (AT -- Parts with same color as final construct--Assemblies_a_Assembly_constructs_with_same_color)

`=IFERROR(join(" 
 ",let(output, unique(arrayformula(trim(bycol(
bycol(O3:V3,
lambda(x,if(x="","",index(dsDNA_d_Input_DNA,xmatch(x,dsDNA_d_ID))))),
lambda(x,if(or(x="",x="anneal"),"",iferror(if(REGEXMATCH(index(Registry_Color,xmatch(x,Registry_Construct_name)), index(Registry_Color,xmatch(E3,Registry_Construct_name))), x,""),"")))))),TRUE), filter(output, output<>""))), "")`

Golden Gate (AH --Parts with same color as final construct--Golden_Gate_g_Assembly_constructs_with_same_color)
`=if(A3="","",
trim(join("
",
bycol(CX3:DG3,lambda(col,ifs(
col="","",
regexmatch(index(Registry_Color,ID_TO_INDEX(col)),AD3),index(Registry_Construct_name,ID_TO_INDEX(col)),
TRUE,"")))))
)`

**Comment by evelynqi** [comment]
Transformations (L--Parts with same color as final construct)

`=if(A3="","",
if(left(A3)="g",index(Golden_Gate_g_Assembly_constructs_with_same_color,xmatch(A3,Golden_Gate_g_ID)), index(Assemblies_a_Assembly_constructs_with_same_color,xmatch(A3,USER_u_ID))))`

**Comment by evelynqi** [comment]
Implemented!

**Comment by evelynqi** [comment]
Um.. it doesn't work for assemblies fully.. will circle back to this.. sorry
Code shouldn't interact else though while it is incorrect...

**Comment by evelynqi** [comment]
Oh.. it was a problem with the code in transformations... I just didn't call the right information. It should be good and implemented now.
