### ISSUE TITLE
Asst: General: Header colors not working as intended

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#221]
I'm assuming that the headers are suppose to turn green when they are in use. E2, F2, etc. headers don't turn green when in the "select single tab, column:" mode.

Also, in the "select different tabs, columns:", row 1 is all highlighted green, even if it says (don't show). I'm not sure if this is intentional or not.

**Comment by bthuronyi** [comment]
Green here is for "required field to be filled in by user". So instead they should be green by default but grayed out with conditional formatting when they aren't relevant.

**Comment by bthuronyi** [comment]
Same for row 1 under "select different tabs, columns" -- it's still required input (and matters -- if you change it, row 2 gets 'unlocked') -- so should be green even when "don't show" is selected.

**Comment by bthuronyi** [comment]
The bigger issue I guess is -- can and/or must Asst: General be made easier to learn to use?

**Comment by bthuronyi** [comment]
But let's leave that for another Issue if needed.

**Comment by evelynqi** [comment]
I see
