### ISSUE TITLE
Experiments -- checking if a construct(ID) exists needs reworking

### ISSUE THREAD

**Issue by evelynqi** [bthuronyi/CloneCoordinate#222]
When I enter g1000 into "Control construct(s) / IDs needed", the status is "g1000:" because we have not gotten to g1000 yet, but the experiment shows up as "Ready" and the status is "ready to start". 

"Required construct not found!" message should be presented in this case.

**Comment by bthuronyi** [comment]
Implemented new Named Functions to (1) validate IDs and (2) get status by ID (and validate in the process), so this now says "ID not found!" for invalid ones.
