### ISSUE TITLE
CC-Tracker: REF error when pulling columns from main sheet

### ISSUE THREAD

**Issue by shen2333333** [bthuronyi/CloneCoordinate#231]
Specifically column BH and CE in imported data column. Maybe column changed in the main sheet?

**Comment by bthuronyi** [comment]
Yep, those have now been removed from main CC. They can be reconstructed using formulas, and the same named range name assigned to them so that references work again seamlessly. I'll whip that up real quick.

**Comment by bthuronyi** [comment]
Also adding additional USER parts columns -- max parts is now 8 instead of 5. These will go live when we rebuild the imported-data tab. That script is nearly ready at last!

**Comment by bthuronyi** [comment]
As I recall, USER_u_Successful_miniprep_achieved_query gave "yes" or "" output -- adjust if you need true/false or something else.

**Comment by bthuronyi** [comment]
Similar for "GG Construct names", I newline-joined the list, tweak if you need something different.
