### ISSUE TITLE
Miniprep manual status related to sample (e.g. ran out) overrides verification

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#238]
If an mID that was previously marked "verified" in Minipreps "What to do" but is later marked e.g. "ran out", then the construct becomes un-verified. Verification will generally take place from Sequencing now, and the specific "ran out" status could be implemented using volumes instead, so this may not come up too much, but it's also kind of a serious bug.

Best approach probably is to have the Minipreps/Sequencing manual "what to do" reconciliation column formula register "verified" from Sequencing and append it to Minipreps even if Minipreps has a manual entry.

**Comment by bthuronyi** [comment]
Unfortunately, "ran out" pre-empts verification even if it arises from manual volume adjust. Need to change this. Verification should always be appended and be independent of "done" vs "don't use" statuses.

**Comment by bthuronyi** [comment]
The properties of the original verified miniprep sample should not change that construct's Registry Status even if it runs out. Doubly true if a verified strain has been made. pAJP035 is a test case where m1479 is actually gone and marking it that way sets pAJP035 as incomplete despite the fact that it's been stored back as a strain.

**Comment by bthuronyi** [comment]
pERQ006 m2056 also has this problem.

**Comment by bthuronyi** [comment]
For now, set pAJP035 and pERQ006 to "Complete (manual override)" in Registry to avoid the practical issue.

**Comment by ethanjeon** [comment]
All verification criteria moved to the end of Minipreps status, to append to status
`
ifs(iferror(
         and(left(L3117)="s",
         index(Strains_s_Storage_strain?,ID_TO_INDEX(L3117)),
         not(regexmatch(index(Strains_s_Status,ID_TO_INDEX(L3117)),"(don't use)")),
         not(regexmatch(CE3117,"(don't use)"))),FALSE)
          ,char(10)&"♥ verified",
    iferror(left(L3117)="r",FALSE), char(10)&"♥ verified",
    iferror(regexmatch(CE3117,"♥"),FALSE),
      iferror(if(regexmatch(BM3117,"All parts verified present"),char(10)&"♥ verified"&if(H3117=""," (from Sequencing)",""),char(10)&"♥ verified"&if(H3117=""," (from Sequencing)","")&char(10)&"sequencing data inconsistent/incomplete for verification?"),""),
TRUE,"")
`

this successfully preserves other stuatuses like 'ran out!'

**Comment by bthuronyi** [comment]
Looks like this covers some cases but not all. 

- Registry Status isn't correctly seeing that they are heart Verified; it seems like it's pulling from a different source column to check this than mID Status (makes sense that it would, to avoid circularity). So we need to find the helper column and have it generate verification.

- Status isn't correctly updating when a "ran out" mID (like m3115) is transformed for strain storage -- and actually "ready to store as strain" or whatever it is should also be able to coexist with "ran out", since we can generally transform an mID even when very little plasmid is available.

In general, it seems like strain storage tasks should be independent of statuses for mIDs like failure due to low conc, running out, etc. because none of these are actually roadblocks to retransforming (it may need more care/attention but can always be done).

**Comment by ethanjeon** [comment]
Fixed Minipreps CB Minipreps_m_Verified_construct_query "Prep from sequence
-verified construct?" - mID verification is now accurate and not confounded by samples running out, being labeled as "(don't use)", etc.
`
=ifs(A3="","",
TRUE,regexmatch(
ifs(
       FALSE,"Note: the code block below must duplicate that in Minipreps_m_Status",
       iferror(
         and(left(L3)="s",
         index(Strains_s_Storage_strain?,ID_TO_INDEX(L3)),
         not(regexmatch(index(Strains_s_Status,ID_TO_INDEX(L3)),"(don't use)")),
         not(regexmatch(CF3,"(don't use)"))),FALSE)
          ,char(10)&"♥ verified",
       iferror(left(L3)="r",FALSE), char(10)&"♥ verified",
       iferror(regexmatch(CF3,"♥"),FALSE), 
         iferror(if(regexmatch(BM3,"All parts verified present"),char(10)&"♥ verified"&if(H3=""," (from Sequencing)",""),char(10)&"♥ verified"&if(H3=""," (from Sequencing)","")&char(10)&"sequencing data inconsistent/incomplete for verification?"),""),
       TRUE,"")
,"♥"))
`

Added Minipreps CC Minipreps_m_Available_construct_query "Prep verified and available?" to filter these accurate verified mIDs based on things like samples running out and "(don't use)" labels
`
=if(and(CB3=TRUE,ifs(A3="","",
regexmatch(CF3,"(don't use)"),FALSE,
and(AS3<>"",AS3<settings_qcLowMiniprepConcCutoff),FALSE,
AG3="no",FALSE,
AI3="",FALSE,
BZ3<=Settings_mMinVolumeLeft,FALSE,
TRUE,TRUE)),TRUE,FALSE)
`

Registry status now shows accurate verification.
