### ISSUE TITLE
dsDNA d "Exclude from analysis?" column - more options

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#24]
dsDNA d "exclude from analysis" could have more reasons (more dropdown options) usefully added.

https://docs.google.com/spreadsheets/d/1xrwFnQ1eCSF4OkF8rvoMA-Njr5CS24l2QnlnsafiQio/edit?disco=AAABNkfKB7A

**Comment by santiagochrist** [comment]
Copied the columns over to a new sheet and took the rows that were not blank and fed it to ChatGPT. Here is what it proposed:

1. Primer Issue
2. Instrument Error
3. Operator Error
4. Sample Integrity and Quality
5. Incomplete Reaction
6. Experimental Design

**Comment by santiagochrist** [comment]
Update: We'll revisit in the future, no need for now.
