### ISSUE TITLE
pBWT046 was marked abandon but still shows queued in registry? 

### ISSUE THREAD

**Issue by shen2333333** [bthuronyi/CloneCoordinate#241]
![image](https://github.com/user-attachments/assets/07af662b-35d0-416f-ad2f-3bec6dc6b73d)
![image](https://github.com/user-attachments/assets/ca5e8c6b-5fa3-472d-94d0-d631a3e103bf)

**Comment by bthuronyi** [comment]
Looks like this is resolved: "What to do with this construct?" in the Registry correctly toggles Abandoned Status.
