### ISSUE TITLE
#VALUE! in dsDNA d Status under certain circumstances

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#243]
When an Assembly has a serial # AND a construct name but no parts, dsDNA d Status becomes #VALUE, b/c of "split parameter 1 value should be non-empty". Presumably about checking for redundancy.

**Comment by bthuronyi** [comment]
Reproduced here:
https://docs.google.com/spreadsheets/d/1LR5raaXym47txtCSnqvaO5IswNftl6V4Iq4Mb7AT3bc/edit?gid=1540456475#gid=1540456475

**Comment by ethanjeon** [comment]
"Function SPLIT parameter 1 value should be non-empty"

Registry BH:BH, where the split error originates:
`
=if(BI1323="","",
**iferror**(join(",",unique(split(join(",",bycol(split(BI1323,","),
lambda(row,join(",",lambda(x,iferror(filter(x,x<>"")))(index(USER_u_Parts,match(row,USER_u_ID,0),)))))),",",TRUE,TRUE),TRUE,FALSE)),""))
`
