### ISSUE TITLE
If aID is queued to transform but a part failed, part failure should override "ready to transform"

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#245]
If an assembly is queued to transform manually (in Transformations), it looks like it will have the "ready to transform" status even if one of its parts is then found to have failed. Instead there should at a minimum be a warning on both Assemblies and Transformations.

**Comment by ethanjeon** [comment]
Warning in Transformation Status
`
&if(iferror(regexmatch(join(",",index('Assemblies a'!AJ:AQ,xmatch(A3,USER_u_ID))),"(don't use)")),"failed part in source aID?",""),
`

Previously implemented warning in Assemblies Status still works
`
countif(AJ3:AQ3,"*(don't use)*")>0,"part failed!",
`
