### ISSUE TITLE
Assemblies/GGs "ready to transform" status doesn't respect Transformation manual status assignment

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#246]
Setting a queued Transformation as "abandon" etc. doesn't seem to change the status in the a or g tab appropriately.

**Comment by ethanjeon** [comment]
Still want to allow for multiple transformations of the same aID/gID, like in specific experiments.

Assemblies and GG Status
`
iferror(regexmatch(index(Transformations_What_to_do_with_this, max(filter(row(Transformations_Source_ID), Transformations_Source_ID=B44))),"(don't use)")),"Recent instance of transformation has been manually terminated - check Transformations sheet?",
`
