### ISSUE TITLE
GG Status (and possibly also Assemblies status) can have "ready to transform / ran out!"

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#248]
"Ran out!" should override "ready to transform" for gIDs and aIDs on their tabs.

**Comment by ethanjeon** [comment]
GG Status, right before the "ready to transform" line
`
sum(iferror(arrayformula(value(split(textjoin(", ",TRUE,filter(Transformations_Transformed_amount,Transformations_Source_ID=B3)),","))),0))>=BF3,"ran out!",
`
Assemblies Status, in analogous spot
`
sum(iferror(arrayformula(value(split(textjoin(", ",TRUE,filter(Transformations_Transformed_amount,Transformations_Source_ID=B3)),", "))),0))>=N3,"ran out!",
`
