### ISSUE TITLE
Asst: sheets don't handle duplicate sort numbers gracefully

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#25]
At least the Asst: minipreps sheet, and possibly others, give many #NUM! errors if duplicate sort numbers are entered. These should be handled differently so no error values appear and some kind of notification should be shown to the user about the duplicated number(s). This code should go on the Asst sheet(s).

**Comment by bthuronyi** [comment]
To get started on this, look at how the Asst sheets look up entries across their columns. Add IFERROR functions where needed. Use ISERROR strategically to catch when something is erroring.

**Comment by evelynqi** [comment]
In the assistant transformation sheet, I added IFERROR statements. In the "Source ID" the new error message says "duplicate sort '#'" and in the other wells, the error messages says "view Source ID" --it could also just be blank for when there is an error. I only implemented it for asst: Transformation sheet (A-G): https://docs.google.com/spreadsheets/d/1YSqAdAVy6jYu_-Nbnop_aQOGMjjLDXzNKm5-Ur23Pcc/edit?usp=sharing

**Comment by evelynqi** [comment]
I also added conditional formatting to the "Sort #" column, where it turns orange when there is an error.

**Comment by evelynqi** [comment]
The rest of the columns' error messages could be done in the same way! And also the other assistant sheets!

**Comment by evelynqi** [comment]
Ready for review: https://docs.google.com/spreadsheets/d/1YSqAdAVy6jYu_-Nbnop_aQOGMjjLDXzNKm5-Ur23Pcc/edit?usp=sharing Asst: Transformation sheet

**Comment by bthuronyi** [comment]
Approved! Looks great. Go ahead and implement on all Asst tabs.

**Comment by evelynqi** [comment]
Update: Implemented fully on assistant transformation and golden gate sheets.

**Comment by evelynqi** [comment]
Update: Implemented fully on the rest of the assistant sheets (dsDNA, Assemblies, Minipreps, Sequencing)
