### ISSUE TITLE
Move Premix columns first in Asst: Assemblies

### ISSUE THREAD

**Issue by santiagochrist** [bthuronyi/CloneCoordinate#255]
Better to pipette small volumes of DNA into half scale volume rather than empty tubes.

**Comment by santiagochrist** [comment]
- B on Santiago's account

**Comment by bthuronyi** [comment]
Done; also added some non-breaking spaces instead of regular spaces in the premix code to make sure volumes stay with the name of the thing being measured (something we could implement elsewhere too).
