### ISSUE TITLE
Sequencing "Well for mixed sample" needs revision for data validation

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#265]
"Well for mixed sample" column in Sequencing should either (a) easier -- have data validation forcing [A-H][01]\d or (b) formula that finds well serial number needs to accept things like "B1" instead of "B01"

**Comment by santiagochrist** [comment]
Done!
<img width="322" alt="Screenshot 2024-11-15 at 7 07 20 PM" src="https://github.com/user-attachments/assets/e3875c01-837e-4552-991f-861eb5f9f087">
`=regexmatch(AC3,"[A-H][01]\d")`

**Comment by santiagochrist** [comment]
Just went for the data validation approach since it's nice to have data be written with a specific format in case we ever want to do something with it.
