### ISSUE TITLE
Assemblies "Miniprep queued?" may not handle retransformations properly

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#28]
Assemblies "Miniprep queued?" column needs to check whether the aID has been retransformed. If so, check whether the latest transformation date is later than the most recent miniprep date, and if so, say "need to queue". (Need to check whether this column needs to be upstream of checks for the construct being completed or not etc. from Status.)

https://docs.google.com/spreadsheets/d/1xrwFnQ1eCSF4OkF8rvoMA-Njr5CS24l2QnlnsafiQio/edit?disco=AAAAu3VeZ3A

**Comment by ixf1** [comment]
My logic: For all rows with the same ID in column B (USER_u_ID), find the largest number in column BS (USER_u_Date_transformed) and largest number in column AA (Minipreps_m_Date_purified) in Minipreps m. If the largest number in column BS is larger than the largest number in column AA for rows with the same ID, output “need to queue”

max(filter(USER_u_Date_transformed, USER_u_ID = B3)) > max(filter(Minipreps_m_Date_purified, USER_u_ID = B3)), "need to queue",

AKA: if(max(filter(BS:BS, B:B = B3)) > max(filter(AA:AA, B:B = B3)), "need to queue"),
Doc: https://docs.google.com/spreadsheets/d/1rNbb51gEX9F9rgchuBS0P25RIhmuet6t6B5BjKNxQhI/edit?gid=790765817#gid=790765817

Error that I'm getting: Wrong number of arguments to IF. Expected between 2 and 3 arguments, but got 4 arguments.

**Comment by ixf1** [comment]
Went through code and commented:
```

=if(or(A3="",BS3=""),"", // If either cell A3 (serial number) or BS3 (Latest date transformed) is empty, return an empty string. 
if(iferror(max(filter(USER_u_Date_transformed, USER_u_ID = B3)) > max(filter(Minipreps_m_Date_purified, Minipreps_m_Source_ID = B3)),FALSE), "need to queue", // My new code! If the maximum number (most recent date) in the USER_u_Date_transformed range for USER_u_ID (B3) is greater than the most recent date in the Minipreps_m_Date_purified range (for Minipreps_m_Source_ID B3), return "need to queue". If error, return FALSE and continue. 
if(iferror(xmatch($B3,Minipreps_m_Source_ID)>0,FALSE),if(len(IFERROR(FILTER(Minipreps_m_Source_ID,Minipreps_m_Source_ID=B3,Minipreps_m_Date_inoculated="")))>0,"queued",if(counta(iferror(filter(Minipreps_m_Construct_name,Minipreps_m_Source_ID=B3,regexmatch(Minipreps_m_Status,"done"))))>0,"done","need to queue")), // If the aID (B3) matches any value in Minipreps_m_Source_ID, go to the nested conditions. If error, return FALSE.
If there are any entries in Minipreps_m_Source_ID where Minipreps_m_Source_ID is the B3 aID and Minipreps_m_Date_inoculated is empty, return "queued".
If there are any entries in Minipreps_m_Construct_name where Minipreps_m_Source_ID is the B3 aID and Minipreps_m_Status contains "done", return "done". Otherwise, return "need to queue".
ifs(
iferror(index(indirect("Registry_Status"),xmatch(E3,indirect("Registry_Construct_name")))="Complete"),"already verified", // If the Registry_Status for the construct name E3 in Registry_Construct_name is "Complete", return "already verified".
or(regexmatch(BU3,"none"),and(H3<>"",H3<>'Settings & admin'!$BJ$5,H3<>'Settings & admin'!$BJ$8)),"don't prep", // If BU3 (Transformation Outcome) contains "none" or H3 (What to do with this sample?) is not empty and not equal to either of the values in 'Settings & admin'!$BJ$5 (Ran out (don't use)) or 'Settings & admin'!$BJ$8 (Hold transformation (assemble, but don't transform)), return "don't prep".
or(H3='Settings & admin'!$BJ$5,and(BS3<>"",BT3="")),"wait", //If H3 equals 'Settings & admin'!$BJ$5 (Ran out (don't use)) or BS3 (Latest date transformed) is not empty and BT3 (Date plates scored) is empty, return "wait".
or(regexmatch(BV3,"don't"),regexmatch(BV3,"can't"),regexmatch(BV3,"no correct colonies")),"can't queue", // If BV3 (Transformation status) contains "don't", "can't", or "no correct colonies", return "can't queue".
TRUE,"need to queue")))) //If everything above is false, return “need to queue”


```

**Comment by ixf1** [comment]
![Beige Organization Chart Graph (1)](https://github.com/bthuronyi/CloneCoordinate/assets/173081691/d26eb57e-6388-4a1c-8e4d-dc0542ae08f4)

**Comment by ixf1** [comment]
if(iferror(max(filter(USER_u_Date_transformed, USER_u_ID = B3)) > max(filter(Minipreps_m_Date_purified, Minipreps_m_Source_ID = B3)),FALSE), "need to queue", 

This is my new code! If the maximum number (most recent date) in the USER_u_Date_transformed range for USER_u_ID (B3) is greater than the most recent date in the Minipreps_m_Date_purified range (for Minipreps_m_Source_ID B3), return "need to queue". If error, return FALSE and continue. 

**The code above works to address this issue, but B and I discussed the column "Minipreps queued?" in comparison to the column "Status" and decided that there are bigger issues. Three places reference "Minipreps queued?" including "Status" and an external sheet, and there is some redundant code., B said to redo the external sheet, and Ethan is fixing the "Status" right now, so he might find the code here useful.**

**Comment by ixf1** [comment]
#40 This is relevant to Ev's code! We are thinking of combining some of the nested if statements and removing the redundancies between the "status" and "minipreps queued?" channels. See below for the consolidated logic flow: 
![Beige Organization Chart Graph (2)](https://github.com/bthuronyi/CloneCoordinate/assets/173081691/443c16a9-7209-4648-ac12-62c8a23eb96b)
