### ISSUE TITLE
Assemblies Status: check about pre-empting assembly or transformation

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#29]
Assemblies get flagged as ready for steps regardless of whether some parts may have failed or the assembly is redundant. Look into this logic and revise appropriately.

**Comment by ethanjeon** [comment]
@bthuronyi Would we want this as an absolute, overriding status for assemblies that are duplicates?  I could do this by referring to the "Duplicate(s)?" column in Assemblies, listing the serial numbers of the duplicate assemblies in the status as well.  Or, should this be appended to the end of most statuses, in case the user might want to queue duplicate assemblies for some reason?

As for the failed parts aspect, I think the current status formula accounts for this up until the point the parts are assembled together.

**Comment by bthuronyi** [comment]
So for duplicate Assemblies, people might definitely queue e.g. "the same" PCR with a few different conditions, not knowing which will work, and then, to make sure things advance automatically, queue up all the different options as different Assemblies. Then if more than one PCR succeeds, I guess you might want to only work with one of them... But on the other hand, it's not clear to me that it's actually a bad idea to keep the redundancy and go forward with multiple tries. They are clearly different in SOME way and who's to say they'll transform the same?

"Redundancy" though also refers to the construct already being completed -- and I think that is currently now handled appropriately, b/c the check for construct abandonment is above everything else.

**Comment by bthuronyi** [comment]
> As for the failed parts aspect, I think the current status formula accounts for this up until the point the parts are assembled together.

This specifically is the issue that could use addressing. If the parts are assembled but, after assembly, we find out that one or more of them definitely failed, I would say we do NOT want to set the assembly status to "ready to transform" but instead to "part failed!" let's say. Because transformation is not an insignificant amount of effort and the likelihood that it works given a failed part is low. (We could check this empirically if we wanted to, but I feel pretty good about it.)

**Comment by bthuronyi** [comment]
> Or, should this be appended to the end of most statuses, in case the user might want to queue duplicate assemblies for some reason?

The "Status" column could definitely be enhanced if we merged duplicate flagging into it, but that's a bigger project potentially. Right now duplicates are shown in separate columns, as you mentioned. We would want to think about which duplicates to add to the Status -- maybe only ones that have not been completed yet should be added to each others' Statuses. But yeah, separate issue, not critical.

**Comment by ethanjeon** [comment]
Quick and easy fix implemented into main CC

Old code for transformation:

**Comment by ethanjeon** [comment]
Quick and easy fix implemented into main CC

Old code for transformation:
`BS3="",if(regexmatch(H3,"don't transform"),"transformation manually held","ready to transform"),`

New code:
`BS3="",ifs(`

`FALSE,"here, added check for failed parts AFTER assembly but BEFORE transformation",`
`countif(AJ3:AQ3,"*(don't use)*")>0,"part failed!",`

`regexmatch(H3,"don't transform"),"transformation manually held",`
`TRUE,"ready to transform"),`

Doesn't change any existing status results, and successfully catches failed parts between assembly and transformation.
