### ISSUE TITLE
Value for oligo GG donor (settings_gOligoDonorDefaultConcentration) needs determining

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#30]
Value for settings_gOligoDonorDefaultConcentration is made up. Instead, it should be based on the concentration expected for a given oligo fragment length at the dilutions specified by CC settings. Ideally, calculate it using a formula that references other Settings rather than entering a numerical value. Check our current Protocol to see what volume we've decided to resuspend gblocks in. Possibly make that volume into a Setting.

https://docs.google.com/spreadsheets/d/1xrwFnQ1eCSF4OkF8rvoMA-Njr5CS24l2QnlnsafiQio/edit?disco=AAAALzTpg0w

**Comment by evelynqi** [comment]
I'm confused -- I'm not sure what you mean. I found settings_gOligoDonorDefaultConcentration in the settings ("10"), but I cannot find where it is used in any formulas... let's talk about it! :)

**Comment by evelynqi** [comment]
Comments from B: concentration in registry should be in ng/µL/kb (nkµ) and in the settings should be (ng/µL). In settings, our lab currently dilutes 500-750ng of DNA with 20µL buffer so the concentration is 25-50ng/µL. In the registry, we should use the sequence/size.

**Comment by evelynqi** [comment]
Ready for review: 
https://docs.google.com/spreadsheets/d/1YSqAdAVy6jYu_-Nbnop_aQOGMjjLDXzNKm5-Ur23Pcc/edit?usp=sharing
Changes implemented in:
Registry(BA)
Settings(P2) --settings_gOligoDonorDefaultConcentration

**Comment by bthuronyi** [comment]
Approach and value look good!

For this line:
"o",settings_gOligoDonorDefaultConcentration/Registry_Construct_size,

You are dividing a single numerical value (settings_gOligoDonorDefaultConcentration) by an array. Instead, you could use INDEX and XMATCH to pull the Registry_Construct_size value that corresponds to the Oligo. BUT since you're already on the Registry tab, and this formula is in each row of column BA, you should just use the value of the Registry_Construct_size column on the same row you're on -- so just reference e.g. cell L3 for row 3. It's not as self-annotating but it saves computation and it's pretty clear.
