### ISSUE TITLE
Minipreps needs to handle when/if multiple mIDs are marked as "validated" manually

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#31]
In Minipreps under "What to do with this sample?", there is no enforcement on multiple mIDs for the same construct being set as "Fully sequence-verified (store this prep)". What should happen if this is done? Maybe institute a Setting about how to handle this -- a checkbox for "enforce only one prep being marked as fully sequence-verified and to be stored". Perhaps as part of handling this, remove the "Also clean (store other prep)" option?

**Comment by evelynqi** [comment]
Thoughts so far: 
-in miniprep, look at if there are minipreps with the same "Construct name" (E) and check to see if there is already a "Stored prep?" (BO) and if it is, if it is a usable prep (Strains_s_Storage_strain?), then change status to done(already stored or smth like that)
-if not, check to see if any of the minipreps with the same "Construct name" (E) are true for "Needs to be stored?" (BP), if yes, this doesn't need to be stored, so change status to done(store another prep or smth like that)

**Comment by evelynqi** [comment]
^ conditional on a Setting about how to handle this -- a checkbox for "enforce only one prep being marked as fully sequence-verified and to be stored"

**Comment by evelynqi** [comment]
Okay, ignore that.

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1qXJL8xT-XuxN5ruPN3QUzeIuULg7BqmcrzEbKLBLIP0/edit?usp=sharing
-currently working on pERQ004 cases (m2052,2053..)

I think we only need to tweak the code in "Needs to be stored?" (BP) so that it accounts for if any other preps with the same construct name that already have "yes" in this category when a Setting about how to handle this -- a checkbox for "enforce only one prep being marked as fully sequence-verified and to be stored is toggled on, but we can't add it into the code like this because that would be circular logic as it is dependent on itself.

I can explain what I mean in person. Let's talk about it.

**Comment by evelynqi** [comment]
a. always store single prep, let them choose or do first one
b. multiple strains can be prepped--thats it

**Comment by evelynqi** [comment]
"Needs to be stored?"
`ifs(
and(regexmatch(H2054,"store this prep"),$BO2054="",$BM2054=FALSE),"yes",
and(regexmatch(H2054,"store a different prep"),$BO2054="",$BM2054=FALSE),"",
TRUE,"")`

To be incorporated into miniprep status:
`=if(settings_mEnforceMaxOnePrepStored?,if(
and(BP2055="yes",not(regexmatch(join(" ",filter(BP4:BP2054, E4:E2054=E2055)),"yes"))),"ready to transform for strain storage",""),
if(BP2055="yes","ready to transform for strain storage",""))`

^^created `settings_mEnforceMaxOnePrepStored?` with description: "Enforce only one prep being marked as fully sequence-verified and to be stored?"

BP/BQ2054

**Comment by bthuronyi** [comment]
> ^^created `settings_mEnforceMaxOnePrepStored?` with description: "Enforce only one prep being marked as fully sequence-verified and to be stored?"

Go ahead and make that setting in main CC! I think we should move forward with implementation once Minipreps Status is ready for this code #138 and that we should see how it handles in a full test case to see what makes sense. I'm having a hard time picturing the truth table of different H values, # of mIDs verified, and settings.

**Comment by evelynqi** [comment]
> Go ahead and make that setting in main CC!

done

**Comment by ethanjeon** [comment]
#153 added some new code in the same exact spot, with a new Setting option:

`ifs(
and(regexmatch(settings_mReadyFlag,"auto"),$BR3="",$BP3=FALSE), char(10)&"ready to transform for strain storage",
and(regexmatch(settings_mReadyFlag,"only"),$BR3="",$BP3=FALSE), if(NOT(regexmatch(H3,"(store this prep)")),"",char(10)&"ready to transform for strain storage"),
TRUE,""),`

I inserted evelynqi's code from above into here, replacing the last `char(10)&"ready to transform for strain storage"`:

`ifs(
and(regexmatch(settings_mReadyFlag,"auto"),$BR3066="",$BP3066=FALSE), char(10)&"ready to transform for strain storage",
and(regexmatch(settings_mReadyFlag,"only"),$BR3066="",$BP3066=FALSE), if(NOT(regexmatch(H3066,"(store this prep)")),"",char(10)&"ready to transform for strain storage"),
TRUE,""),`

and got a circular dependency error -_-

**Comment by bthuronyi** [comment]
With @evelynqi:

- Had Minipreps Status just incorporate a check to BS (Needs to be stored?) wherever it was going to generate the "ready to transform for strain storage" message
- Changed Needs to be stored? code
   - Respect setting settings_mEnforceMaxOnePrepStored? first
   - If setting is on, then if multiple mIDs are manually marked to store, output "yes" only for the first mID in the list (by looking at What to do with this sample?, stored as strain already column, and "don't store" column)
   - works!
