### ISSUE TITLE
Warn if an mID is marked clean without supporting data

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#32]
In Minipreps "What to do with this sample?" you can mark an mID as sequence-verified even if it hasn't been sequence-verified according to CC. In this case, have Status throw a warning (but without preventing "verified" marking).

**Comment by santiagochrist** [comment]
Right now Status checks on Column BW ("Prep from sequence-verified construct?"), which is marked as "true" when the "What to do with this sample?" flag is enabled.

This is most likely done to easily override the Status manually, but I'd rather keep Column BW more faithful to its purpose, i.e., be a true sequence verification check **as opposed** to a check that can just be manually adjusted.

Prep from sequence-verified construct? (BW):
-
```
=if(A263="","",
iferror( 
and(
left(K263)="s", // strain ID
index(Strains_s_Storage_strain?,ID_TO_INDEX(K263)), // storage strain?
index(Strains_s_Verified?,ID_TO_INDEX(K263)), // verified correct?
not(regexmatch(H263,"(don't use)")) // not "not don't use"
),
FALSE)) // mark false as default for the iferror
```
Status (E):
-
```
...&
ifs(
BW263,char(10)&"♥ verified", // if BW263 is now "faithful", then being true means that the sequence truly is verified
H263="Fully sequence-verified (store this prep)",char(10)&"♥ verified"&char(10)&"?" // however, if BW263 is false but we manually set H263 to sequence-verified, then we put the same "♥ verified" message but with a "?" to cause conditional formatting to make the cell yellow
      )&
...
```
Let me know what you think about this approach @bthuronyi.

**Comment by santiagochrist** [comment]
Update:
-
- No need to adjust Column BW.
- We instead want to look at the registry summary from Column BI.
- Verify that the text "All parts verified present" is in the summary, indicates good sequencing.

Column BI:
-
```
...&
ifs(
   regexmatch(BI256,"All parts verified present"),char(10)&"♥ verified", // if the text is present, all is good
   BW256,char(10)&"♥ verified"&char(10)&"?") & // otherwise look at the manual check, with a warning '?'
...
```

**Comment by santiagochrist** [comment]
Final Code:
-
- Removed Column BW and added over its code to our new solution.
- Added case for rID, where rIDs (whose validity is checked by another cell) are automatically verified.
- Otherwise, see the below logic diagram.

```
...&
ifs(
       iferror(and(left(K2444)="s",index(Strains_s_Storage_strain?,ID_TO_INDEX(K2444)),not(regexmatch(H2444,"(don't use)"))),FALSE),char(10)&"♥ verified",
       iferror(left(K2444)="r",FALSE), char(10)&"♥ verified",
       iferror(regexmatch(H2444,"♥"),FALSE), iferror(if(regexmatch(BH2444,"All parts verified present"),char(10)&"♥ verified",char(10)&"♥ verified"&char(10)&"sequencing data missing?"),""),
       TRUE,""
      )&
...
```
![IMG_1575](https://github.com/user-attachments/assets/71a3e369-3ede-4753-9310-048c6e99ad00)
