### ISSUE TITLE
Add Origins dropdown options

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#34]
In Registry "Origin of replication" column, add data validation dropdown options that live in Settings. Base these on the Origins we've previously tabulated in the Registry. See B or look manually on Benchling to find out whether groups of registered origins are identical or different. Consider splitting this column into origin and compatibility group??

**Comment by evelynqi** [comment]
Okay, let's talk about it and compatibility groups.

**Comment by evelynqi** [comment]
Compatibility groups for settings:

-pUC/pMB1/pBR322/ColE1
-SC101
-p15a
-RSF1010
-CloDF13
-Other

**Comment by evelynqi** [comment]
Use regexmatch formula to fill in

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1l7FTz599mQRtRKJ22gTEKHh-tkxkMDrYpmAAl_V1TwI/edit?usp=sharing
-Implemented "Registry: Origin compatibility groups" (settings_registryOriginCompatibilityGroupTable) under the Registry: Antibiotics table
-Added new column in Registry (P-Compatibility group/origin family) and filled it out using a regexmatch formula:
=ifs(
$Q1291="","",
regexmatch($Q1291,"(pUC)|(pMB1)|(pMBR322)|(ColE1)"),"pUC/pMB1/pMB1-M/pBR322/ColE1",
regexmatch($Q1291,"SC101"),"SC101",
regexmatch($Q1291,"p15a"),"p15a",
regexmatch($Q1291,"RSF1010"),"RSF1010",
regexmatch($Q1291,"CloDF13"),"CloDF13",
TRUE,"Other")

**Comment by bthuronyi** [comment]
Looks good! Let's use the Arrow style for the data validation (under Advanced options). Please implement in main

**Comment by evelynqi** [comment]
Done.
