### ISSUE TITLE
Robust colors/highlighting for wells / plates in Asst sheets

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#37]
Ideally, Asst sheets should have color cues that show you which samples are IDENTICAL vs. not (based on well/plate) and which samples are on THE SAME vs on DIFFERENT plates. We have various approaches to this coded, like highlighting based on plate number, but they aren't comprehensive and aren't elegantly scaled.

**Comment by santiagochrist** [comment]
I think that keeping the colors for the plate #s would work well for me at least, but as for identical samples I think that **_bolding and italicizing_** the well location would help me spot the difference. We could make the text red or something else to help it stand out if needed, since I don't think there are many conditional formatting rules that alter text color, so we could reserve it for this case. 

The current approach takes the third digit on a well location (i.e., m13 -> 3, s05 -> 5, m23 -> 3) and fills in a unique color based on that digit, which in my opinion is not a bad option since the code works fine until m/s/d/a99. It is hard-coded to take the third digit, though.

Another option is that we could mess with color scales instead of having solid fills in the cells, but that might be more work than it's worth. I also like the solid fill colors that are already in the assistant sheets, so let me know what you think.

**Comment by bthuronyi** [comment]
> It is hard-coded to take the third digit, though.

I think this is the key problem. It's common that we might use e.g. m13 and m23 at the same time, and they're actually extra confusable because of sharing a digit.

What I'd especially like for this issue is:

- [x] Generate a dynamic list of all the plate identifiers (m13, m23, m08, d01, d02)
- [x] Sort them - probably just SORT is good enough (d01,d02,m08,m13,m23)
- [x] Assign serial numbers within each category (1,2,1,2,3)
- [x] Assign highly distinguishable colors based on serial number (red, blue, red, blue, yellow -- or whatever)

Practically, that would look like some number of helper columns -- it would be fine to implement a solution that needed 1 helper column per cell we need to color, but eventually we would want to get it down to say 2 cells (one containing the wells and one containing the serial numbers; you could then SPLIT and INDEX/XMATCH in the conditional formatting code itself).

**Comment by santiagochrist** [comment]
I have accomplished the first three checkboxes, will probably discuss with you to see what we want to do with colors but I'll come up with some color system of my own before we talk to see if it'd work. 

With that being said, I achieved a 2 helper column solution just for organization, although we can indeed condense the code down to 2 literal cells if we wanted (I'm not sure if this is what you wanted haha).

Well List:
-
`=sort(tocol(filter(left(I3:I,4),regexmatch(I3:I,"[mdsoar]\d{2,}\."))))`

Well Serial No.:
-
Row 3: If the well list column is non-blank, then we start at 1.
`=if(G3="","",1)`
Row >3: Every subsequent row follows a sequence that uses the previous/next row.
`=if(left(G3)=left(G4),F3+1,1)`

Screenshot:
-
<img width="160" alt="Screenshot 2024-07-24 at 4 36 52 PM" src="https://github.com/user-attachments/assets/aa7ca00a-dc2d-4301-aa46-60f130c85434">

**Comment by bthuronyi** [comment]
Nice. I guess with that filter you can pull in an entire large swath of the Asst tab by first FLATTENing it. Keep in mind we want to do this formatting on basically every well ID that appears in the user-facing parts of each Asst tab.

For the serial number, I recommend:
`sequence(countif(G3:G,"<>"))` in the first row, that'll output the array you want.

**Comment by santiagochrist** [comment]
Conditional Formatting:
-
`=let( serial_number, iferror(if(H3="",-1,filter(F3:F,regexmatch(G3:G,left(index(H3),4)))),-1), if(serial_number=1,true,false) )`
`=let( serial_number, iferror(if(H3="",-1,filter(F3:F,regexmatch(G3:G,left(index(H3),4)))),-1), if(serial_number=2,true,false) )`
`=let( serial_number, iferror(if(H3="",-1,filter(F3:F,regexmatch(G3:G,left(index(H3),4)))),-1), if(serial_number=3,true,false) )`
`...`
`=let( serial_number, iferror(if(H3="",-1,filter(F3:F,regexmatch(G3:G,left(index(H3),4)))),-1), if(serial_number=7,true,false) )`

Can't seem to apply this range dynamically? I think the previous code did this, where row K (well column 2) needs every H3 changed to K3, etc.

**Comment by santiagochrist** [comment]
Update: Had to lock ($) the ranges, haha.

Final Code: Minipreps Example
-
Conditional Formatting:
`=let( num, 1, serial_number, iferror(if(E3="",-1,index($AI$3:$AI,xmatch(left(index(E3),4),$AJ$3:$AJ))),-1), if(serial_number=num,true,false) )`

Well Serial #:
`=if(AJ3="","",1)`

Well List:
`=ifs(
AJ4="","",
AJ3=AJ4,AI3,
left(AJ3)=left(AJ4),AI3+1,
true,1)`

Color Pattern:
![Screenshot 2024-07-25 at 4 06 06 PM](https://github.com/user-attachments/assets/a42b3022-e38f-4d7e-bcd9-6239f80317e0)
