### ISSUE TITLE
Asst: GG premix throws error sometimes

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#42]
Asst: GG "µL in premix" column gives #DIV/0! I think when all assemblies with sort numbers have been completed already. Handle this better - don't throw an error, instead hide the component(s) / leave blank.

**Comment by bthuronyi** [comment]
Related to #123

**Comment by santiagochrist** [comment]
Could it be as simple as...

Row K3:
```
=iferror(
if(
A3="","",if(regexmatch($H$1,"Premix enabled"),sum($BK$3:$BK),"")
),
"Completed already" // Take the division by 0 error and output this message
)
```

And applying this conditional formatting for range `M3:AO3`, placed first in the hierarchy:
`=$K3 = "Completed already" // if K3 gives warning message, gray/cross out cells`

**Comment by bthuronyi** [comment]
https://docs.google.com/spreadsheets/d/1ziLDJyqw1qKeowfPWMGHoT_diWgqxYsWNtYaOVb__Yg/edit?gid=1540456475#gid=1540456475

**Comment by bthuronyi** [comment]
> Could it be as simple as...
> 
> Row K3:
> 
> ```
> =iferror(
> if(
> A3="","",if(regexmatch($H$1,"Premix enabled"),sum($BK$3:$BK),"")
> ),
> "Completed already" // Take the division by 0 error and output this message
> )
> ```
> 
> And applying this conditional formatting for range `M3:AO3`, placed first in the hierarchy: `=$K3 = "Completed already" // if K3 gives warning message, gray/cross out cells`

Yeah, this looks like it would work at a glance. We may also decide to hide the premix elements themselves, though, rather than hiding their display in the columns, depending on how reviewing the premix code goes. Both reasonable options.

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1O8Lp268wTBJHQs242kHXhCU1ayhEZRmO4Oi8lVBwGAc/edit?usp=sharing

Implemented different header names for calculated versus what you actually mix. It looked at the calculated, which disappears for completed constructs, and that would have led to the DIV/0 error for completed constructs queued in the assistant gg sheet.
