### ISSUE TITLE
Add labeled sections to tabs to specify different work stages

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#51]
Highlight or block off different sections of tabs that reflect different work stages - e.g. queueing, inoculation, prep, QC, sequencing for mIDs - across all entities. Ideally, label each section clearly so that the contents can be referred to explicitly. ("Go to the Inoculation section of the Minipreps tab...")

It's not obvious to me how to implement this except by using Merge Cells. That looks really good and works fine with Named Ranges, but I'm not sure if there's some downside. We would need to look into that and think carefully.

**Comment by bthuronyi** [comment]
One relevant factor here is whether we can use the existing and lightly used 1st header row for this purpose. It would look nice! So let's see how much we are currently using that row across tabs.

- Oligos o - just 1 link in the frozen portion at left
- dsDNA d - column H had a message about sort #s; moved this to the frozen portion
- however... dsDNA d and several other places will use this space for "default" values to paste. So we definitely need to preserve those cells, AND those cells will often be in the same area that we would want to designate with a merged-cell "label". So it's looking like we CANNOT use the existing row 1 for these.

**Comment by bthuronyi** [comment]
An alternative approach: color code blocks of such cells, and label the 1st column in each one using a Row 1 cell. This will probably not overlap with Defaults much. The Row 1 cells could be color coded...

**Comment by bthuronyi** [comment]
Down-side is that it would make it more difficult to call attention to Row 1 warning or error messages, where those are used, by conditional formatting transition from white to colored.

**Comment by bthuronyi** [comment]
Change: Add identifiers in header area for distinct "sections" or "blocks" of columns on most tabs
Why: Allows you to direct someone to a general area of a tab -- e.g. "the queueing section," "the quant section", "the strain storage section" -- in a way that's impossible now
Questions: How to implement?
We currently have 2 header rows; row 2 has column titles and row 1 has messages/errors/warnings and default values for copy-paste
Option 1: If we want to keep 2 header rows, we could color each section's row 1 cells differently, and label the section at its start column in row 1. There would be room for this.
But it would mean any messages to the user in row 1 couldn't be made as noticeable by giving them conditional formatting color backgrounds
It would also be fairly busy
Option 2: We could add a 3rd header row. In that case, each section could be labeled in that row, and we could merge cells within such a row so that each section has "one" cell labeling it, with the label centered across the section.
This would let you click into the new label header row and then scroll section-by-section using the arrow keys -- nice for navigation!
It would add some more vertical space to all tabs (though we could make it shorter than other rows)
It would potentially require a LOT of random formula changes in Analytics and other separate Sheets that draw from CC
CC itself would update formulas like "'Oligos o'!$C$3:$C" automatically to "'Oligos o'!$C$4:$C", but sheets that draw data from it via IMPORTRANGE would not update automatically
But we might want to make such Sheets robust toward changes like this anyway
Coding best practices (under development) ask you to only use Named Ranges to engage with imported data in formulas, and such formulas would be completely robust to this change since they involve entire columns by definition
So maybe we should just get all the Analytics etc. sheets in compliance anyway
Option 3: too hard / not worth it, don't do

Creating a demo Sheet; see first 5 tabs
https://docs.google.com/spreadsheets/d/1oEca1JBiG-XP9CDJPqXxQ1Jh6iaQRHxrR_q_SegeHxc/edit?gid=1129314706#gid=1129314706 (edited)

**Comment by santiagochrist** [comment]
I created a table using Notion where I keep track of all of the working stage names, cell ranges, and color palettes, to be implemented following the meeting on July 9. 

https://tinyurl.com/summer24issue51

Here is a little snapshot if the link is ever dead:

<img width="800" alt="Screenshot 2024-07-08 at 2 40 57 PM" src="https://github.com/bthuronyi/CloneCoordinate/assets/173081947/a01efc44-3293-4b52-8739-0f93d7004b59">

**Comment by santiagochrist** [comment]
Colors have been implemented on all pipeline tabs + registry, ready for review @bthuronyi.

**Comment by santiagochrist** [comment]
Color guide:
<img width="787" alt="Screenshot 2024-07-10 at 10 05 42 AM" src="https://github.com/bthuronyi/CloneCoordinate/assets/173081947/de16009c-320d-42e4-b7c0-3751c1b3b7b3">

**Comment by bthuronyi** [comment]
Looks like there are still some font, alignment and wrapping anomalies -- all these entries should be Roboto Mono, left aligned and overflow. I also see a few incorrect color orders, that could use a quick review.

The order you implemented doesn't follow reverse ROYGBIV, though there's an argument to be made that not following that helps with distinguishability, and when I consider the pros and cons it seems like that's more important than being able to tell at a glance where you are horizontally in the task order -- the horizontal scroll bar does that for you!

In terms of distinguishability though, I might swap Text2 for something else, maybe Text5 or Text9. 1-2 and 2-3 differences are less stark than all the other ones.

**Comment by bthuronyi** [comment]
As I mentioned live, this particular feature addition has really grown on me -- I'm not sure how we got away with leaving where each "task section" started and ended so vague for so long. This arrangement not only lets you refer to sections by number within a sheet ("look at dsDNA d 2a" or "look at dsDNA d queueing, general") but also makes clear what required/option fields need to be filled out to complete each task.

**Comment by bthuronyi** [comment]
There is a lesson there -- this seemed fairly inessential and its importance only emerged during/after late stage implementation. You can't always judge accurately how important something will be before doing some amount of work on it.

**Comment by bthuronyi** [comment]
Unexpected challenge with the cell borders interacting with "default" values in Header 1... the border gets pasted unless you paste-as-values... 😭 

Fortunately there is a solution. For sections that contain defaults (or for all sections, doesn't really matter but it might be better for consistency...) we need to apply the border to the _top of row 2_ rather than the _bottom of row 1_. There is no visual difference but it means when you copy a row 1 cell you don't get the formatting too.

**Comment by santiagochrist** [comment]
Done and done, think all should be good now @bthuronyi.

**Comment by bthuronyi** [comment]
Awesome! Looks great!!
