### ISSUE TITLE
Date data validation

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#52]
Validate all Date fields sensibly and accurately.

**Comment by bthuronyi** [comment]
Can use data validation against a regular expression to do this, using Custom Formula and a formula with REGEXMATCH. Consider requiring that all years be >2010 and making sure that months are 01-12 and days are 01-31. Use regex101.com for testing!

**Comment by santiagochrist** [comment]
Using the following regular expression to vali/date (Row 3 as an example):
`=REGEXMATCH(`
`TEXT(I3, "000000"), // sheets only uses string-based regex matching, second param refers to YYMMDD format`
`"^(1[1-9]|[2-9][0-9]) // year should be between 11-99` 
`((0[1-9]|1[0-2]|00) // month should be in range 01-12, 00 is allowed if month is unknown`
`(0[1-9]|[12][0-9]|3[01]|00))$" // day should be in range 01-31, 00 is allowed if day is unknown`
`)`

**Comment by santiagochrist** [comment]
Added the condition as a Data Validation rule, works well on my copy. Note that live CC uses Row G instead of I. Otherwise, I'm ready to deploy the solution.

**Comment by santiagochrist** [comment]
**Simplified the Regex:**
`=REGEXMATCH(`
`TEXT(I3, "000000"), // same as above`
`"^([1-9][\d]) // year in range 10-99`
`((0[\d]|1[0-2]) // month in range 00-09 OR 10-12`
`([0-2][\d]|3[01]))$" // day in range 00-29 OR 30-31`
`)`

**Comment by santiagochrist** [comment]
When using the "Custom formula" under data validation, **I don't think that cell references are dynamic?** If we want to make the data validation only one rule and apply it to various date columns (ranges), then they would all still refer to column I3:I used in the example above. I might be missing something, but let me know if there is another workaround to this @bthuronyi:

`=REGEXMATCH(`
`TEXT(INDIRECT(ADDRESS(ROW(), COLUMN()), // my try at a dynamic cell reference for use in data validation`
`"^([1-9][\d]) // unchanged`
`((0[\d]|1[0-2]) // unchanged`
`([0-2][\d]|3[01]))$" // unchanged`
`)`

Line 2 makes date entry feel quite sluggish!

**Comment by bthuronyi** [comment]
I verified that Custom formula DOES use dynamic cell referencing, so you should be able to go with your original version.

![image](https://github.com/bthuronyi/CloneCoordinate/assets/141874213/6de1275b-81ba-4577-8337-0a2b5a298877)

**Comment by santiagochrist** [comment]
Applied the formula to every date field I could find, feel free to check out the data validation range.
