### ISSUE TITLE
Audit and improve "PCR template DNA" field in dsDNA d

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#58]
"PCR template DNA" field in dsDNA d can accept several types of template, but doesn't always check whether they're ok to use and may not be fully built out. Check Status and Queueing validity check column logic to make airtight.

**Comment by bthuronyi** [comment]
https://docs.google.com/spreadsheets/d/1xrwFnQ1eCSF4OkF8rvoMA-Njr5CS24l2QnlnsafiQio/edit?disco=AAAArmPV5AA

@[bwt2@williams.edu](mailto:bwt2@williams.edu) Might as well allow this to recognize rIDs
B Thuronyi
B Thuronyi
Jun 8, 2023 (edited Jun 8, 2023)
Make it clearer when template is not recognized during queueing
B Thuronyi
B Thuronyi
Jun 8, 2023
@[bwt2@williams.edu](mailto:bwt2@williams.edu) Add 1) support for manual m# entry; 2) double-check that 'verified' template checking is working as expected
B Thuronyi
B Thuronyi
May 11, 2021
@[bwt2@williams.edu](mailto:bwt2@williams.edu) Add support for 'o' well if used.
Show less
B Thuronyi
B Thuronyi
Jun 8, 2023
Make sure prep selected is valid

**Comment by ethanjeon** [comment]
Updated dsDNA status to handle rIDs (using same chunk of 'switch' code from the queueing validity).  Looks good, including template DNA handling in the assistant sheet.
