### ISSUE TITLE
Generic "Asst" sheet, read

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#61]
Separate sheet that lets you view information about an arbitrary set of entities from CC side by side. Could display fixed set of info based on the ID type, or let you flexibly display different columns selected from a dropdown... could get very complex, but start simpler!

**Comment by shen2333333** [comment]
I just got started on this:
1. One dropdown specify the specific "tab" to read , e.g. Oligo o
2. Another dropdown specify the column to read, e.g. column A

Here's a demo, see if it's on the right track.
 https://docs.google.com/spreadsheets/d/1kuqv-l_HXsf4cdSIRtx-bgVXxN6pwX1l7Up65Sz8Axg/edit?usp=sharing

**Comment by bthuronyi** [comment]
Nice, this is a good start. What I would really like is to have drop-down options that show not the column letter but instead, say, the value in row 2 for that column (the descriptive header) in column order. That feels like it would be enough info to use it without having to click back and forth to the source tab.

Then for the column contents, we would want to let the user enter which ID(s) to show data for, and look up the corresponding rows for each column.

**Comment by shen2333333** [comment]
Currently support up to 7 columns (could add more if necessary,), and arbitrary number of IDs, see example images below 
![image (4)](https://github.com/bthuronyi/CloneCoordinate/assets/174066091/870caed9-ab63-4f05-a037-fe54c6d87d01)
![image (5)](https://github.com/bthuronyi/CloneCoordinate/assets/174066091/1ebc146a-b248-429a-98d2-179e2df028a9)

**Comment by shen2333333** [comment]
@bthuronyi Thanks for the further improvement! I consider it done, any further adjustment will be minor.

**Comment by bthuronyi** [comment]
Tweaked a little further, allowing user to specify whether they want to pull column entries from a single tab or from multiple different tabs, in a dropdown. Implemented in main CC and opened for group comments.
