### ISSUE TITLE
Minipreps Status plate availability for inoculation needs adjusting

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#67]
If a plate from which mIDs are supposed to be inoculated is marked as not available in Transformations, the mIDs should show up as not ready. Conversely, if a recent plate is available but an older one is not, the mIDs should show up as ready. However the current Status code only checks for the first plate encountered in Transformations, not the most recent one or for any available one.

@[bwt2@williams.edu](mailto:bwt2@williams.edu) Fix code for "transformation not available" so it only checks LATEST queued transformation for this entity, not any of them
B Thuronyi
B Thuronyi
Jul 6, 2023
Actually do this using the "Plate status" column formula instead, and parrot it directly, maybe fold it fully in later

https://docs.google.com/spreadsheets/d/1xrwFnQ1eCSF4OkF8rvoMA-Njr5CS24l2QnlnsafiQio/edit?disco=AAAA0bhiX-4

**Comment by ixf1** [comment]
_- If a plate from which mIDs are supposed to be inoculated is marked as not available in Transformations, the mIDs should show up as not ready. Conversely, if a recent plate is available but an older one is not, the mIDs should show up as ready. However the current Status code only checks for the first plate encountered in Transformations, not the most recent one or for any available one._
- For the instances of Transformations_Source_ID matching the Minipreps_m_Source_ID for this row, find the one with the largest number (most recent date) in Transformations_Date_scored. If the corresponding  Transformations_What_to_do_with_this contains “don’t use”, output “Not ready”. Else output an empty string
`=if(regexmatch(index(transformations_what_to_do_with_this, xmatch(max(if(transformations_source_id = K3, transformations_date_scored)), if(transformations_source_id = K3, transformations_date_scored))), "don't use"), "not ready", ""),
`

_- Fix code for "transformation not available" so it only checks LATEST queued transformation for this entity, not any of them… Actually do this using the "Plate status" column formula instead, and parrot it directly, maybe fold it fully in later_
- If there are many instances of Transformations_Source_ID matching the Minipreps_m_Source_ID for this row, find the one with the largest number (most recent date) in Transformations_Date_queued. If the corresponding Transformations_What_to_do_with_this is not empty, output "transformation not available".
`=if(regexmatch(index(Transformations_What_to_do_with_this, xmatch(max(if(Transformations_Source_ID = K3, Transformations_Date_Queued)), if(Transformations_Source_ID = k3, Transformations_Date_Queued))), "don't use"), "transformation not available", ""),
`

**Comment by ixf1** [comment]
`=if($W3<>"","", // W3 is Date inoculated
switch(left($K3), // K3 is ID 
"a",let(transform_date,iferror(index(USER_u_Date_transformed,xmatch($K3,USER_u_ID))), // K3 is ID 
ifs(
  transform_date="","not transformed!",
  value(datedif(DATE_YYMMDD(transform_date),today(),"D"))>Settings_mPlateAge,"questionable",
  TRUE,"OK")),
"g",let(transform_date,iferror(index(Golden_Gate_g_Date_transformed,xmatch($K3,Golden_Gate_g_ID))),
ifs(
  transform_date="","not transformed!",
  value(datedif(DATE_YYMMDD(transform_date),today(),"D"))>Settings_mPlateAge,"questionable",
  TRUE,"OK")),
"s","",
""))`

@bthuronyi Question: What is the purpose of the repeated code above? Does it have to do with the "a," "g," and "s"? This is the original code for plate status in minipreps m. I highlighted the repeated parts below:

![image](https://github.com/bthuronyi/CloneCoordinate/assets/173081691/b2878c88-c700-4546-acc1-5ab6580a221f)

Also, when I try to implement my code in the comment above, there is always a formula parse error. Could we look at that together? Ev already tried to help me.
