### ISSUE TITLE
Registry "Suggested sequencing primer(s)" should suggest whole-plasmid for large constructs

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#68]
Add code to Registry "Suggested sequencing primer(s)" to suggest whole-plasmid sequencing based on cost effectiveness and a Setting or two. Add Setting for size threshold above which to recommend whole-plasmid, or number of Sanger oligos, or do cost calculation... first option is simplest!

**Comment by evelynqi** [comment]
Changed Registry (column V); https://docs.google.com/spreadsheets/d/1YSqAdAVy6jYu_-Nbnop_aQOGMjjLDXzNKm5-Ur23Pcc/edit?usp=sharing

r1164 is a fun example, suggested sequencing now is "whole plasmid sequencing" (V1166) and matches your inputted "Whole-plasmid) (T1166).

**Comment by bthuronyi** [comment]
Looking good! I think the check for whether whole-plasmid is more cost-effective should go at the top before Sanger gets recommended (so, after "verify parts present" but before oligos get outputted). Otherwise this looks good to implement, including the Named Ranges in Settings. 

I recommend these names:

Settings_Registry_SizeBackbone > Settings_Registry_ExpectedMinSizeBackbone
Settings_Registry_BasesPerOneOligoRead > Settings_Registry_SangerReadAverageBases
Settings_Registry_SangerCostPerOligo > Settings_Registry_SangerReadCost
Settings_Registry_WholePlasmidSeqCost looks good!

The new area of Settings could be folded into the existing Sequencing Options area. The cells for the named ranges should have light green background to show required user input.

**Comment by evelynqi** [comment]
Done!

**Comment by evelynqi** [comment]
Note: Cannot add formatting to code. Need assistance please.

**Comment by bthuronyi** [comment]
We found that the issue here is that when Protected Ranges are set to "warn before editing", if a user makes whitespace-only changes to a formula (newlines, spaces) in a Protected cell, then even if they click "ok" on the warning popup to commit the edit, it will revert it automatically. The solution is for sure to make a non-whitespace edit at the same time (which you can then revert afterward), and probably also to click the "don't show this message for 5 minutes" before trying to do whitespace-only changes.

**Comment by evelynqi** [comment]
Adding non-whitespace edits does work to make the newlines, but once those edits are deleted, the format reverts back to one block of text...

**Comment by evelynqi** [comment]
Update: it works for all but one cell...
