### ISSUE TITLE
Minipreps "Is sequencing appropriate?" needs to check growth phenotype

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#73]
"Is sequencing appropriate?" should flag mIDs where growth color or phenotype doesn't match expectation as "check QC" or even better "unexpected growth phenotype"

**Comment by santiagochrist** [comment]
Did we more or less solve this with the other **Minipreps "Is sequencing appropriate?"** issue @bthuronyi ?

**Comment by bthuronyi** [comment]
Yes, looks good!
