### ISSUE TITLE
Golden Gate queueing validity check needs to be split up with Status

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#74]
GG "Queueing validity check" needs sorting out into things that go into Status and things that stay there. At present, the formula doesn't fully short-circuit when the certification is checked. Instead, anything that still needs calculating after the queueing stage should be moved over to Status and only calculated between the queued and assembled stages.

**Comment by bthuronyi** [comment]
From Queueing validity check but needs to move into Status:
`ifs(
countblank(ED3:EM3)=column(EM3)-column(ED3)+1,"no mIDs used yet",
and(ED3:EM3),"valid mIDs",
TRUE,"INVALID mID! "&join(" ",byrow(filter(AU3:BD3,ED3:EM3=FALSE),lambda(row,row&"="&index(Registry_GG_parts_display_name,xmatch(index(Minipreps_m_Construct_name,xmatch(row,Minipreps_m_ID)),Registry_Construct_name)))))&"
"&`
because mIDs aren't assigned during queueing but instead before assembly.

Likewise the next block, same reason:
`if(and(byrow(filter(AU3:BD3,ED3:EM3=FALSE),lambda(row,
let(ActualmIDConstructName,index(Minipreps_m_Construct_name,xmatch(row,Minipreps_m_ID)),
and(
index(Registry_5_overhang,xmatch(ActualmIDConstructName,Registry_Construct_name))=index(Registry_5_overhang,xmatch(DP3,Registry_ID)),
index(Registry_3_overhang,xmatch(ActualmIDConstructName,Registry_Construct_name))=index(Registry_3_overhang,xmatch(DP3,Registry_ID))))))),
"junctions remain valid","INVALID junctions")),
"Validity check function error!"))`

**Comment by bthuronyi** [comment]
Queueing validity check probably also needs more basic stuff like "are all the fields filled in"

**Comment by bthuronyi** [comment]
At a glance, Status looks appropriate (nothing from Status that should be moved into Queueing validity check and isn't there already)

**Comment by ethanjeon** [comment]
Moved over + added some blank cell checks in queueing validity
