### ISSUE TITLE
Handling of temperature sensitivity/growth medium/growth temp

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#75]
Handle temperature sensitivity, growth temps - probably use a different table in Settings and Registry - and flag Transformations, Minipreps, Strain storage and their Asst sheets based on these...

**Comment by evelynqi** [comment]
I'm curious to what you mean by handling these. My assumption is that in settings, there is a block dedicated to users inputting their standard conditions and in the other sheets, there is a column that users can input their values into. In the header, the default could draw directly from the user input in settings, but they would have to fill out the column based on what they actually did. Thoughts?

**Comment by bthuronyi** [comment]
Yeah haha this wasn't extensively documented in the Issue, was it?? What you describe does make sense to do -- we want/need to track actual growth temperatures and media. I think any steps that involve growths in liquid culture should have columns for these. The core issue is that some strains/plasmids _require particular growth conditions_. For example a temperature sensitive plasmid MUST be grown at the permissive temperature or it is likely to be lost. Other times you may need to add something to the culture or use a particular medium. So the support we need is that any time a user is inoculating a culture or growing a plate, we need to flag prominently for them any conditions that _require_ a particular temperature/media. If they are required to fill in a growth medium / temperature field BEFORE the actually inoculate/grow, that can work, because we can flag any discrepancies between the required and actual values. But either way, these situations will usually be rare, and therefore unexpected, so we should have a warning in the header of e.g. the Asst tab to draw users' attention to them whenever they arise.

Temperature could come up for any plasmid being cloned b/c it tends to be a plasmid property, or it could be a strain property too even without plasmid. Special media conditions are most likely to come up for Strains rather than Plasmids. Generally during cloning we only use a basic cloning strain and not specialized host cells, though I guess there could be some exception. But a strain stored in the -80 and then e.g. inoculated to miniprep could well have special growth medium requirements.

So this affects the Strains tab as well as Registry, Minipreps, Transformations... lots of stuff across CC. A big project with many details!

**Comment by evelynqi** [comment]
So far, I have implemented a Growth temperature (˚C) col into the miniprep and strain sheets. Need to learn how to add ˚C automatically. The transformation sheet already has a growth temperature col.

- [ ] add to registry
- [ ] add defaults to settings & to banners
- [ ] add to asst sheets

**Comment by bthuronyi** [comment]
> Need to learn how to add ˚C automatically.

It's "custom number formatting" and the easiest way is to just copy and paste-formatting-only from another column that has it. But the details are in Format > Number > Custom number format

**Comment by bthuronyi** [comment]
> * add to asst sheets

One perhaps useful thing to do is use the code for assigning PCR blocks in Asst: dsDNA to raise warnings about growth temperature for samples that are purportedly in the same plate but need different temps. Though this reminds me that we need to handle different options for how people grow their miniprep cultures... maybe track it as well...

**Comment by evelynqi** [comment]
- [x] Add special conditions to Registry (generalized--data validation from settings table perhaps?)
- [x] Minipreps, Transformations, Strains should have the Intended Special conditions (pulled from registry) and what they actually input (what they actually input col is blue so they don't have to fill it out but it will have conditional formatting for cases where they need to fill it out
- [x] Corresponding asst sheets should definitely SHOW the conditions and have a banner with color that saids PAY ATTENTION TO SPECIAL CONDITIONS

**Comment by evelynqi** [comment]
Done! https://docs.google.com/spreadsheets/d/1bzumeOTEN57T3ak3pbLISh5hERLXs2nSg6Wq2Fliesw/edit?usp=sharing

1. Added "Specific growth conditions" (Registry O-Registry_Specifc_growth_condition) to the Registry
2. Added "Specific growth conditions" (R) and "Actual growth conditions" (Z) to the Miniprep sheet. The latter has conditional formatting (I picked an arbitrary color for now, I'm sure we have a system of colors) which lights up the cell if there are specific growth conditions inputted and they were not recorded in the actual growth conditions. I could make it so that once a value is inputted and it doesn't match the intended value, it turns a different color. Added note: "Cell will warn you when there are specific conditions needed to be followed. Check 'Specific growth conditions' in 1. Sample properties on this sheet"
3. Same thing as 2 for transformation and strains tab
-Specific growth conditions (J) and Actual growth conditions(W) in transformations
-Specific growth conditions (J) and Actual growth conditions (S)
4. Added specific growth conditions to asst miniprep (L) and asst transformation tabs (J) with note: "Be wary of specific growth conditions; these constructs may need to be grown separately of others due to these condition" with conditional formatting on the individual cells that have the specific growth conditions. Maybe it needs to be flashier but I think it is noticeable.

**Comment by bthuronyi** [comment]
> * Added "Specific growth conditions" (R) and "Actual growth conditions" (Z) to the Miniprep sheet. The latter has conditional formatting (I picked an arbitrary color for now, I'm sure we have a system of colors) which lights up the cell if there are specific growth conditions inputted and they were not recorded in the actual growth conditions. I could make it so that once a value is inputted and it doesn't match the intended value, it turns a different color. Added note: "Cell will warn you when there are specific conditions needed to be followed. Check 'Specific growth conditions' in 1. Sample properties on this sheet"
> * Same thing as 2 for transformation and strains tab
>   -Specific growth conditions (J) and Actual growth conditions(W) in transformations
>   -Specific growth conditions (J) and Actual growth conditions (S)

Nice. We might end up putting these as a warning in Status to further raise the prominence. This is good for the moment.

**Comment by bthuronyi** [comment]
> 4\. Added specific growth conditions to asst miniprep (L) and asst transformation tabs (J) with note: "Be wary of specific growth conditions; these constructs may need to be grown separately of others due to these condition" with conditional formatting on the individual cells that have the specific growth conditions. Maybe it needs to be flashier but I think it is noticeable.

I think this is good -- the colors stand out quite a bit since normally these are just gray and white. We could also add a message in the header row that appears if the column isn't blank and highlight that. I'll leave it up to you if you want to add it.

**Comment by bthuronyi** [comment]
- [x] Note "Registry_Specifc_growth_condition" should be "Registry_Specific_growth_condition"

**Comment by bthuronyi** [comment]
- [x] When implementing, please update the (few) constructs in Registry that have "TS 30 degrees" in Marker 2, and then remove that option from the Marker list in Settings

**Comment by bthuronyi** [comment]
Looks great overall, go for it in main!
