### ISSUE TITLE
"Template DNA well" in Asst: dsDNA fails on mIDs

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#76]
"Template DNA well" in Asst: dsDNA fails on mIDs and possibly other kinds of Template.

**Comment by santiagochrist** [comment]
As a starting point, I've tried to deconstruct some of the logic going on. I wanted to start with mIDs, so I identified this code segment:
```
...
left(BM3)="m", // If the PCR template DNA is an mID
iferror(
if(
index('Minipreps m'!$BU$3:$BU, // Obtain the Volume left from Minipreps using below position
xmatch(BM3,'Minipreps m'!$B$3:$B) // Compare the PCR template mID to all mIDs, get position
)>Settings_dTemplateMiniprepMinVolumeLeft, // If it is greater than the 5 uL threshold 
Settings_dTemplateMiniprepMinVolumeLeft, // IF TRUE: Return 5 uL???
index( // IF FALSE:
'Minipreps m'!$C$3:$C, // Obtain the well location using below position 
match(BM3,'Minipreps m'!$B$3:$B,0)),""), // Compare the PCR template mID to all mIDs, get position
"Invalid mID?" // If we get an error, could be caused by an invalid mID
), 
...
```
Want to understand: (1) why are we returning 5 uL minimum volume, (2) why do we only return well position if the volume left is NOT greater than the "Miniprep Min Volume Left" (aka <5 uL)?

Now that code is commented, we should discuss tomorrow @bthuronyi when possible.

**Comment by santiagochrist** [comment]
Case: We have the identifier.
- If PCR Template DNA is some kind of ID (oID, sID, mID, dID), then use custom function `ID_TO_WELL`.
- Converts identifier to location.

Case: Construct name and NOT identifier.
- If not identifier, we can assume construct name inputted.
- Much more complicated stuff, we keep the old code for now but it's ok since the Asst tab does not take more than 100 rows.

```
=ifs(
BM3="","",
regexmatch(left(BM3), "[mosd]"),ID_TO_WELL(BM3),
TRUE,iferror(index(filter(Minipreps_m_Well,Minipreps_m_Construct_name=BM3,Minipreps_m_Volume_left>Settings_dTemplateMiniprepMinVolumeLeft, regexmatch(Minipreps_m_Status, "done"), regexmatch(Minipreps_m_Status, "♥")), 1), "Not found?"))
```
