### ISSUE TITLE
PCRs should check availability of template mID based on its Status

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#90]
If a PCR lists an mID as template, it should check its Status and show an error/warning (not Ready) if it ran out or is marked discard etc.

**Comment by santiagochrist** [comment]
I talked with Ethan, and we agreed that if the status of the template mID is not "done", then it is reasonable to throw out a warning message (i.e., as opposed to matching every individual error/warning case):
```
=ifs(A393="","",
and(Settings_analytical_PCR_NoAbandonedConstructs,iferror(index(Registry_Status,xmatch(I393,Registry_Construct_name)))="Abandoned"),"construct abandoned",
NOT(regexmatch(filter(Minipreps_m_Status, Minipreps_m_ID = C393), "done")), "check status!", // STATUS CHECK
U393<>"",
...
```

**Comment by santiagochrist** [comment]
Update: Ethan is currently working on the Status column. I will make a new copy of CC in which the mID is listed as "Don't use," etc., under Minipreps m. When Ethan implements fix, I'll check to see if the issue still exists.

**Comment by santiagochrist** [comment]
Update: Works now, marked as "template failed!", which is denoted by the block below. Thank you, Ethan!
```
not(or(regexmatch(status,"done"),regexmatch(status,"complete"))),
if(regexmatch(status,"(don't use)"),"template failed!","wait; need template"),
```
