### ISSUE TITLE
Sequencing should wait on dID QC in some circumstances

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#92]
If a dID is queued for sequencing and is marked as high priority gel or quant, Sequencing should probably wait to have it mixed until that QC is finished. This could be an optional Setting. It should also DEFINITELY disqualify dIDs from being sequenced if they fail QC.

**Comment by evelynqi** [comment]
Notes: Pull from d sheet using regexmatch(indexmatch, phrase) for QC results

**Comment by evelynqi** [comment]
Ready for review: 
https://docs.google.com/spreadsheets/d/1YSqAdAVy6jYu_-Nbnop_aQOGMjjLDXzNKm5-Ur23Pcc/edit?usp=sharing

CHANGES:
-Sequencing status (Sequencing F) changes to "do not sequence (low conc)", "do not sequence (failed assembly)", and "wait on QC" respectively and pulls from the status of the dsDNA on the dsDNA sheet
-Added to Settings the option to wait on having QC finished (Settings CW5: "Require QC data before marking dIDs as ready to queue for sequencing?" and CX5: settings_SequencingRequireQC?)

**Comment by evelynqi** [comment]
Questions: 
-Should it also pull gel problems?
-Should it say if it's been sequenced before?

**Comment by bthuronyi** [comment]
Overall approach looks great!
- Yes, gel problems should translate to a warning - I think we only have "warn" level gel QC analysis in dsDNA Status as of now
- Yes, as with mIDs a warning of previous sequencing would be good

I think you can use something like
`and(settings_SequencingRequireQC?, index(dsDNA_d_Date_quant,xmatch(A3,dsDNA_d_ID))=""`
as one test-value pair in IFS, so that you don't need to duplicate the later code.

"(failed assembly)" should be "(failed dID)" (to cover all types)

Make sure your REGEXMATCH tests are appropriate -- you may need to include a "!" or "?" character to distinguish between possible statuses that mention conc or failed -- but I didn't check, so maybe it's fine. This is the kind of Status standardization that @ethanjeon is working through. A major overall goal should be to provide consistent types of status messages so that we can REGEXMATCH on appropriate strings and know what we'll get.

**Comment by evelynqi** [comment]
Done!
Update: 
-Got rid of the duplicate code using the and()
-Added gel results

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1YSqAdAVy6jYu_-Nbnop_aQOGMjjLDXzNKm5-Ur23Pcc/edit?usp=sharing

Sequencing (F)

**Comment by bthuronyi** [comment]
Looks good! We might consider changing the "gel" and "conc" flags to sound like warnings rather than errors -- like, "check gel before mixing" or "concentration may be too low?"

E.g. a later line for mID checking has:
`and(E3="Whole-plasmid",N3<30),"ready to mix "&"("&E3&") - conc risky!",`

There, the sample *is* marked "ready to mix" in addition to the warning. dIDs should probably behave similarly.

**Comment by evelynqi** [comment]
Update: Implemented on copy sheet. 

https://docs.google.com/spreadsheets/d/1YSqAdAVy6jYu_-Nbnop_aQOGMjjLDXzNKm5-Ur23Pcc/edit?usp=sharing
Sequencing (F)

**Comment by evelynqi** [comment]
CHANGED
ORIGINAL:
left(A3)="d",if(iferror(index('dsDNA d'!$AX$3:$AX,match(A3,'dsDNA d'!$B$3:$B,0)))<>"","ready to mix "&"("&E3&")","wait on d"),

NEW:
left(A3)="d",
 let(dsDNA_status,index(dsDNA_d_Status,xmatch(A3,dsDNA_d_ID)),
 ifs(
  index(dsDNA_d_Date_finished,xmatch(A3,dsDNA_d_ID))="","wait on d",
   and(settings_SequencingRequireQC?,index(dsDNA_d_Date_quant,xmatch(A3,dsDNA_d_ID))=""),"wait on QC",
     regexmatch(dsDNA_status, "conc"), "ready to mix "&"("&E3&")"&" - concentration may be too low?",
     regexmatch(dsDNA_status, "failed"), "failed dID!",
     regexmatch(dsDNA_status, "gel"), "ready to mix "&"("&E3&")"&" - check gel before mixing!",
     TRUE,"ready to mix "&"("&E3&")")),
