### ISSUE TITLE
Sequencing "Omit from order?" should override "data ready?"

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#93]
"Omit from order = TRUE" should override "data ready?" so that one can fill in - or " " to allow skipping to next "wait for data" row.

**Comment by ethanjeon** [comment]
Seems to be fixed when status logic is rearranged to be chronological experimentally (placing mixing before alignment)

**Comment by ethanjeon** [comment]
Resolved alongside issue #91 in massive Sequencing status overhaul
