### ISSUE TITLE
Golden Gate "Queue analytical PCR?" needs to account for completed constructs

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#98]
Golden Gate "Queue analytical PCR?" needs to account for completed constructs and maybe also gIDs that are stalled because of phenotypes not being appropriate or low colonies. Overhaul formula.

**Comment by bthuronyi** [comment]
"@[zs2@williams.edu](mailto:zs2@williams.edu) I think this needs to account for completed constructs, and maybe some other things too. Otherwise it will just keep growing, as I read it.
B Thuronyi
B Thuronyi
Mar 6, 2023
I also don't think the formula will ever hit the AB="" condition because IFS is short-circuit evaluated, it will match the first true condition, and here you have 'true' as a line above the AB="" check. Swapping the order will fix it."

**Comment by santiagochrist** [comment]
Tested on my copy of CC, let me know! Using Row 3 as an example:

`=if(B3<>"",`
`ifs(`
`or(DF3="don't prep",DL3="yes", $F3="construct abandoned", $F3="transformed; stalled"),"don't queue",`
`AD3="",""`
`true,"possible to queue",`
`),`
`"")`

As noted, the Golden gate status column (F) already references the registry, so we can simply pull data from column F.

**Comment by bthuronyi** [comment]
I think that'll do it! There is some unclarity in my mind about whether we should test for exact match (as you do) of the whole text string or whether we should choose a substring that closely captures the sense of the message and use REGEXMATCH to test for it. The latter is more robust to our tweaking the Status output language. But at some point, we are going to freeze the Status output language... and maybe will need to be comfortable doing search and replace within formulas if we do want to change it. So this is probably fine as-is.

Actually! There is a situation where we need to be careful about this, which is for Status fields that can have things appended to them. And that's... all of them, I think, due to Priority flagging, which adds "(priority)" to the end of the string. But the same sense should apply, which is, do we REGEXMATCH on the entire string we expect, or on a part of it. I can't really decide what's better, I guess using the entire string.

**Comment by bthuronyi** [comment]
So in this case you would want to use:

```
=if(B3<>"",
ifs(
or(DF3="don't prep",DL3="yes", regexmatch($F3,"construct abandoned"), regexmatch($F3,"transformed; stalled")),"don't queue",
AD3="",""
true,"possible to queue",
),
"")
```

**Comment by santiagochrist** [comment]
LGTM, just tested it on my copy of CC. Let me know if you'd like to implement it on live CC.

**Comment by bthuronyi** [comment]
Go for it!

**Comment by santiagochrist** [comment]
Fixed a few commas, final code:
```
=if(B3<>"", // if gID is not blank, test everything below 
ifs(or(DF3="don't prep",DL3="yes", regexmatch($F3,"construct abandoned"), regexmatch($F3,"transformed;  stalled")),"don't queue", // if any of these conditions apply, we don't queue
AD3="","", // if we read no marker, do nothing
true,"possible to queue" // if all tests pass, we can queue
),
"") // if gID is blank, we output blank
```
